### ISSUE TITLE
InvalidSizeError when downloading an object with content-encoding:gzip using fget_object 

### ISSUE THREAD

**Issue by benbro** [minio/minio-py#1026]
fget_object fail to download an object with content-encoding:gzip.
Version 6.0.0

Create tar.gz file:
```
echo 'Hello' >> test.txt
tar -czvf test.tar.gz test.txt
```

```python
bucket = 'b'
# upload object
minio.fput_object(bucket, 'test.txt', 'test.tar.gz', content_type='text/plain', metadata={'Content-Encoding': 'gzip'})

# this is working
response = minio.get_object(bucket, 'test2.txt')

# throws an error
minio.fget_object(bucket, 'test.txt', 'test3.txt')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/minio/api.py", line 835, in fget_object
    raise InvalidSizeError(msg)
minio.error.InvalidSizeError: InvalidSizeError: message: Data written 6 bytes is in excess than the specified size 127 bytes
```

**Comment by harshavardhana** [comment]
This issue is because urllib3 is auto ungzipping the content due to content-encoding

**Comment by balamurugana** [comment]
@benbro Please use `get_object()` instead of `fget_object()` for your use case.

**Comment by benbro** [comment]
This is still a bug.

**Comment by balamurugana** [comment]
@benbro Feel free to send a fix.

**Comment by benbro** [comment]
Whether I'll send a fix or not is not relevant. This is a bug and the issue shouldn't be closed.
