### ISSUE TITLE
put_object hangs on HTTP 413

### ISSUE THREAD

**Issue by kruserr** [minio/minio-py#1116]
## Current Behavior
Given an Nginx proxy used for TLS termination infront of Minio.
Nginx  has a default `client_max_body_size` of 1MB.

Attempting to `put_object`  larger than 1MB returns a HTTP 413 as observed in Nginx logs.
The Python Minio client hangs.

## Expected Behavior
Raise exception to indicate that a HTTP 413 occurred.

**Comment by harshavardhana** [comment]
We retry requests there should be no hang, make sure to fix your nginx configuration.

**Comment by kruserr** [comment]
> 
> 
> We retry requests there should be no hang, make sure to fix your nginx configuration.

There is no problem with the nginx config.
It is just to illustrate the problem.

However it seems to retry forever?

**Comment by balamurugana** [comment]
@kruserr Please share the below detail
1. Make sure you are using the latest version of `minio-py v7.0.4`.
2. Enable HTTP tracing using `Minio.trace_on()` and share the output.

**Comment by kruserr** [comment]
> 
> 
> > We retry requests there should be no hang, make sure to fix your nginx configuration.
> 
> There is no problem with the nginx config.
> It is just to illustrate the problem.
> 
> However it seems to retry forever?

Why retry on a 413 though, don't we already know that it will not succeed the next time, and loop forever?

**Comment by balamurugana** [comment]
> > > We retry requests there should be no hang, make sure to fix your nginx configuration.
> > 
> > 
> > There is no problem with the nginx config.
> > It is just to illustrate the problem.
> > However it seems to retry forever?
> 
> Why retry on a 413 though, don't we already know that it will not succeed the next time, and loop forever?

The latest `minio-py` does not retry on failures. Please provide necessary information mentioned in https://github.com/minio/minio-py/issues/1116#issuecomment-866075552

**Comment by kruserr** [comment]
> 
> 
> @kruserr Please share the below detail
> 
>     1. Make sure you are using the latest version of `minio-py v7.0.4`.
> 
>     2. Enable HTTP tracing using `Minio.trace_on()` and share the output.

```
---------START-HTTP---------
GET /test-bucket?location= HTTP/1.1
Host: *REDACTED*
User-Agent: MinIO (Linux; x86_64) minio-py/7.0.4
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20210622T153039Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210622/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 200
Date: Tue, 22 Jun 2021 15:30:36 GMT
Content-Type: application/xml
Content-Length: 128
Connection: keep-alive
Vary: Accept-Encoding
Vary: Origin
Content-Security-Policy: block-all-mixed-content
X-Amz-Request-Id: 168AF1379C7DA5DA
X-Xss-Protection: 1; mode=block
Strict-Transport-Security: max-age=15724800; includeSubDomains
X-Cache-Status: MISS
Accept-Ranges: bytes

<?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/"></LocationConstraint>
----------END-HTTP----------
---------START-HTTP---------
POST /test-bucket/data/harmonie/test_50mb_file.bz2?uploads= HTTP/1.1
Content-Type: application/octet-stream
Host: *REDACTED*
User-Agent: MinIO (Linux; x86_64) minio-py/7.0.4
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20210622T153039Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210622/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 200
Date: Tue, 22 Jun 2021 15:30:36 GMT
Content-Type: application/xml
Content-Length: 276
Connection: keep-alive
Vary: Accept-Encoding
Vary: Origin
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
X-Amz-Request-Id: 168AF1379D9B49B6
X-Xss-Protection: 1; mode=block
Strict-Transport-Security: max-age=15724800; includeSubDomains

<?xml version="1.0" encoding="UTF-8"?>
<InitiateMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Bucket>test-bucket</Bucket><Key>data/harmonie/test_50mb_file.bz2</Key><UploadId>51373174-b48b-464d-a0ad-581b5f3e7829</UploadId></InitiateMultipartUploadResult>
----------END-HTTP----------
---------START-HTTP---------
PUT /test-bucket/data/harmonie/test_50mb_file.bz2?partNumber=1&uploadId=51373174-b48b-464d-a0ad-581b5f3e7829 HTTP/1.1
Host: *REDACTED*
User-Agent: MinIO (Linux; x86_64) minio-py/7.0.4
Content-Length: 10485760
Content-Md5: 3+388T4VfEdS5WKw0RkEew==
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20210622T153039Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210622/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

---------START-HTTP---------
PUT /test-bucket/data/harmonie/test_50mb_file.bz2?partNumber=2&uploadId=51373174-b48b-464d-a0ad-581b5f3e7829 HTTP/1.1
Host: *REDACTED*
User-Agent: MinIO (Linux; x86_64) minio-py/7.0.4
Content-Length: 10485760
Content-Md5: TfwWxz2sikb9PZDhX4bPCQ==
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20210622T153039Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210622/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

---------START-HTTP---------
PUT /test-bucket/data/harmonie/test_50mb_file.bz2?partNumber=3&uploadId=51373174-b48b-464d-a0ad-581b5f3e7829 HTTP/1.1
Host: *REDACTED*
User-Agent: MinIO (Linux; x86_64) minio-py/7.0.4
Content-Length: 10485760
Content-Md5: kyrOfHRqPUB0/JLt/H67zA==
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20210622T153039Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210622/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
```

**Comment by balamurugana** [comment]
@kruserr I don't see response for `PUT` call. Not sure why your server doesn't respond to those calls.

**Comment by kruserr** [comment]
Now it seems to crash on dev machine, but after ~3min timeout.
On prod machine, i got no crash.

```
---------START-HTTP---------
GET /test-bucket?location= HTTP/1.1
Host: *REDACTED*
User-Agent: MinIO (Linux; x86_64) minio-py/7.0.4
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20210622T153039Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210622/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 200
Date: Tue, 22 Jun 2021 15:30:36 GMT
Content-Type: application/xml
Content-Length: 128
Connection: keep-alive
Vary: Accept-Encoding
Vary: Origin
Content-Security-Policy: block-all-mixed-content
X-Amz-Request-Id: 168AF1379C7DA5DA
X-Xss-Protection: 1; mode=block
Strict-Transport-Security: max-age=15724800; includeSubDomains
X-Cache-Status: MISS
Accept-Ranges: bytes

<?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/"></LocationConstraint>
----------END-HTTP----------
---------START-HTTP---------
POST /test-bucket/data/harmonie/test_50mb_file.bz2?uploads= HTTP/1.1
Content-Type: application/octet-stream
Host: *REDACTED*
User-Agent: MinIO (Linux; x86_64) minio-py/7.0.4
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20210622T153039Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210622/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 200
Date: Tue, 22 Jun 2021 15:30:36 GMT
Content-Type: application/xml
Content-Length: 276
Connection: keep-alive
Vary: Accept-Encoding
Vary: Origin
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
X-Amz-Request-Id: 168AF1379D9B49B6
X-Xss-Protection: 1; mode=block
Strict-Transport-Security: max-age=15724800; includeSubDomains

<?xml version="1.0" encoding="UTF-8"?>
<InitiateMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Bucket>test-bucket</Bucket><Key>data/harmonie/test_50mb_file.bz2</Key><UploadId>51373174-b48b-464d-a0ad-581b5f3e7829</UploadId></InitiateMultipartUploadResult>
----------END-HTTP----------
---------START-HTTP---------
PUT /test-bucket/data/harmonie/test_50mb_file.bz2?partNumber=1&uploadId=51373174-b48b-464d-a0ad-581b5f3e7829 HTTP/1.1
Host: *REDACTED*
User-Agent: MinIO (Linux; x86_64) minio-py/7.0.4
Content-Length: 10485760
Content-Md5: 3+388T4VfEdS5WKw0RkEew==
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20210622T153039Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210622/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

---------START-HTTP---------
PUT /test-bucket/data/harmonie/test_50mb_file.bz2?partNumber=2&uploadId=51373174-b48b-464d-a0ad-581b5f3e7829 HTTP/1.1
Host: *REDACTED*
User-Agent: MinIO (Linux; x86_64) minio-py/7.0.4
Content-Length: 10485760
Content-Md5: TfwWxz2sikb9PZDhX4bPCQ==
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20210622T153039Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210622/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

---------START-HTTP---------
PUT /test-bucket/data/harmonie/test_50mb_file.bz2?partNumber=3&uploadId=51373174-b48b-464d-a0ad-581b5f3e7829 HTTP/1.1
Host: *REDACTED*
User-Agent: MinIO (Linux; x86_64) minio-py/7.0.4
Content-Length: 10485760
Content-Md5: kyrOfHRqPUB0/JLt/H67zA==
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20210622T153039Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210622/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

---------START-HTTP---------
DELETE /test-bucket/data/harmonie/test_50mb_file.bz2?uploadId=51373174-b48b-464d-a0ad-581b5f3e7829 HTTP/1.1
Host: *REDACTED*
User-Agent: MinIO (Linux; x86_64) minio-py/7.0.4
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20210622T153342Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210622/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 204
Date: Tue, 22 Jun 2021 15:33:40 GMT
Connection: keep-alive
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Vary: Origin
X-Amz-Request-Id: 168AF16251A5C274
X-Xss-Protection: 1; mode=block
Strict-Transport-Security: max-age=15724800; includeSubDomains


----------END-HTTP----------
Traceback (most recent call last):
  File "*REDACTED*/harmonie/src/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "*REDACTED*/harmonie/src/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "*REDACTED*/harmonie/src/venv/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1049, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.8/http/client.py", line 971, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 15, in <module>
    client.put_object('test-bucket', f"data/harmonie/{file_name}", f, -1, part_size=10*1024*1024)
  File "*REDACTED*/harmonie/src/venv/lib/python3.8/site-packages/minio/api.py", line 1809, in put_object
    raise exc
  File "*REDACTED*/harmonie/src/venv/lib/python3.8/site-packages/minio/api.py", line 1787, in put_object
    result = pool.result()
  File "*REDACTED*/harmonie/src/venv/lib/python3.8/site-packages/minio/helpers.py", line 722, in result
    raise self._exceptions_queue.get()
  File "*REDACTED*/harmonie/src/venv/lib/python3.8/site-packages/minio/helpers.py", line 674, in run
    result = func(*args, **kargs)
  File "*REDACTED*/harmonie/src/venv/lib/python3.8/site-packages/minio/api.py", line 1651, in _upload_part_task
    return args[5], self._upload_part(*args)
  File "*REDACTED*/harmonie/src/venv/lib/python3.8/site-packages/minio/api.py", line 1644, in _upload_part
    result = self._put_object(
  File "*REDACTED*/harmonie/src/venv/lib/python3.8/site-packages/minio/api.py", line 1620, in _put_object
    response = self._execute(
  File "*REDACTED*/harmonie/src/venv/lib/python3.8/site-packages/minio/api.py", line 413, in _execute
    return self._url_open(
  File "*REDACTED*/harmonie/src/venv/lib/python3.8/site-packages/minio/api.py", line 280, in _url_open
    response = self._http.urlopen(
  File "*REDACTED*/harmonie/src/venv/lib/python3.8/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "*REDACTED*/harmonie/src/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "*REDACTED*/harmonie/src/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "*REDACTED*/harmonie/src/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "*REDACTED*/harmonie/src/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "*REDACTED*/harmonie/src/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='*REDACTED*', port=443): Max retries exceeded with url: /test-bucket/data/harmonie/test_50mb_file.bz2?partNumber=3&uploadId=51373174-b48b-464d-a0ad-581b5f3e7829 (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
```

**Comment by balamurugana** [comment]
@kruserr You are getting `ConnectionResetError: [Errno 104] Connection reset by peer` which means your server is closing connection for `PUT` calls. There is no problem with `minio-py`.

**Comment by kruserr** [comment]
@balamurugana Alright, thanks for the insight!

The hang issues seems to be related with `minio-py/7.0.3`.
