### ISSUE TITLE
Listener crashes after listening for 500 seconds.

### ISSUE THREAD

**Issue by neuneck** [minio/minio-py#1125]
Using the listener in its EventIterables form (as it is on master right now), it crashes for me after listening for 490~500 seconds. 
I believe the issue is caused by the `EventIterables.__next__()` method being recursing and a possible state where the `EventIterables._stream` object always yields an empty response of some kind. This would not trigger a reactivation of the listener request itself

To reproduce, run a local minio server using 
```bash
docker run --rm -it --name minio -p 9000:9000 \
  -e "MINIO_ROOT_USER=therootuser" \
  -e "MINIO_ROOT_PASSWORD=foobarbaz" \
  minio/minio:RELEASE.2021-06-07T21-40-51Z server /mnt/data
```
and execute the following script:
```py
from minio.api import Minio
import time
from threading import Thread


minio = Minio(
    endpoint="127.0.0.1:9000",
    access_key="therootuser",
    secret_key="foobarbaz",
    secure=False)

print("Set up minio_client")

start = time.time()
end_print = start + 900


def print_timer():
    """Print the time every 10 seconds."""
    while time.time() < end_print:
        time.sleep(10)
        print(f"Time elapsed: {time.time() - start}")


time_printer = Thread(target=print_timer, daemon=True)
time_printer.start()

with minio.listen_bucket_notification(
    bucket_name="foo",
    prefix="foo",
    events=["s3:ObjectCreated:*"]
) as events:
    print("Starting to listen...")
    for event in events:
        print(event)
```

This outputs:
```
Set up minio_client
Starting to listen...
Time elapsed: 10.010317087173462
Time elapsed: 20.016552209854126
...
Time elapsed: 450.38057708740234
Time elapsed: 460.3885717391968
Time elapsed: 470.3965768814087
Time elapsed: 480.4046263694763
Time elapsed: 490.41264128685
Traceback (most recent call last):
  File "pure_minio_test.py", line 34, in <module>
    for event in events:
  File "/home/julian/.virtualenvs/minio_test/lib/python3.8/site-packages/minio/datatypes.py", line 802, in __next__
    return self._get_records() or self.__next__()
  File "/home/julian/.virtualenvs/minio_test/lib/python3.8/site-packages/minio/datatypes.py", line 802, in __next__
    return self._get_records() or self.__next__()
  File "/home/julian/.virtualenvs/minio_test/lib/python3.8/site-packages/minio/datatypes.py", line 802, in __next__
    return self._get_records() or self.__next__()
  [Previous line repeated 988 more times]
  File "/home/julian/.virtualenvs/minio_test/lib/python3.8/site-packages/minio/datatypes.py", line 786, in _get_records
    line = self._stream.__next__().strip()
  File "/home/julian/.virtualenvs/minio_test/lib/python3.8/site-packages/urllib3/response.py", line 572, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/julian/.virtualenvs/minio_test/lib/python3.8/site-packages/urllib3/response.py", line 764, in read_chunked
    self._update_chunk_length()
  File "/home/julian/.virtualenvs/minio_test/lib/python3.8/site-packages/urllib3/response.py", line 694, in _update_chunk_length
    line = self._fp.fp.readline()
  File "/usr/lib/python3.8/socket.py", line 664, in readinto
    self._checkReadable()
RecursionError: maximum recursion depth exceeded
```

**Comment by balamurugana** [comment]
@neuneck Please try this PR https://github.com/minio/minio-py/pull/1126

**Comment by neuneck** [comment]
@balamurugana Tried it, it works well. Thank you for the quick response!
