### ISSUE TITLE
progress.py abends with ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by russdan** [minio/minio-py#1127]
Hi. I am trying to use the Progress() indicator with a simple 

```
import minio as Minio
import progress as Progress()
client = Minio(site, user, secret secure=False)
result = client.fput_object(bucket, object_name, file_name, progress=Progress())
```

most of the time I get the following abend :

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "russtest.py", line 97, in run
    self.print_status(current_size=self.current_size,
  File "russtest.py", line 133, in print_status
    formatted_str = prefix + format_string(
  File "russtest.py", line 167, in format_string
    frac = float(current_size) / total_length
ZeroDivisionError: float division by zero
```

From my debug it looks like in `run() `when the task `display_queue .get `returns `Empty` the final `self.print_status()` call with `current_size=0` and `total_length=0` causes the error (as the `total_length=0` causes the divide by zero error).

Fix is to remove the `except` `self.print_status()` call in `run` and this seems to work as expected without the abend, ie
```
    def run(self):
        displayed_time = 0
        while True:
            try:
                # display every interval secs
                task = self.display_queue.get(timeout=self.interval)
            except Empty:
                elapsed_time = time.time() - self.initial_time
                if elapsed_time > displayed_time:
                    displayed_time = elapsed_time
                continue
```

**Comment by balamurugana** [comment]
Reopen if you see this problem again.
