### ISSUE TITLE
Issue using listen_bucket_notification.py: AttributeError: __enter__

### ISSUE THREAD

**Issue by MatinF** [minio/minio-py#1132]
I'm trying to replicate this example:

https://github.com/minio/minio-py/blob/master/examples/listen_bucket_notification.py

However, when I run the example, I get below error:

```
Traceback (most recent call last):
  File "C:\Users\marti\Downloads\from minio import Minio.py", line 17, in <module>
    "canlog1", prefix="E01DB066/", events=["s3:ObjectCreated:*", "s3:ObjectRemoved:*"],
AttributeError: __enter__
```
Any ideas?

**Comment by balamurugana** [comment]
1. Use the latest version of `minio-py`
2. Share your code having this issue
3. Enable `Minio.trace_on()` and share the output

**Comment by MatinF** [comment]
1. I have now updated to the latest version of `minio-py`
2. I'm trying to run the below code:

```
client = Minio(endpoint, access_key=access_key, secret_key=secret_key, secure=secure)

with client.listen_bucket_notification(
    bucket_name="canlog1", prefix="E01DB066/", events=["s3:ObjectCreated:*", "s3:ObjectRemoved:*"],
) as events:
    for event in events:
        print(event)
```

However, when I do I now receive the below error:
```
Traceback (most recent call last):
  File "C:\Users\marti\Downloads\minio_listen.py", line 16, in <module>
    for event in events:
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\minio\datatypes.py", line 845, in __next__
    self._response = self._func()
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\minio\api.py", line 899, in <lambda>
    preload_content=False,
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\minio\api.py", line 415, in _execute
    no_body_trace=no_body_trace,
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37\lib\site-packages\minio\api.py", line 389, in _url_open
    raise response_error
minio.error.S3Error: S3 operation failed; code: NotImplemented, message: A header you provided implies functionality that is not implemented, resource: /canlog1, request_id: 169457F5E900DF39, host_id: 0fdff802-4913-43ce-afc7-62a3886ca9b2, bucket_name: canlog1
```

Note that I'm able to verify the connection to the MinIO S3 server by using `found = client.bucket_exists("canlog1")`.

**Comment by harshavardhana** [comment]
S3 gateway does not support ListenBucketNotification @MatinF

**Comment by MatinF** [comment]
Hi again,

Thanks for clarifying. 

I'm running MinIO as an S3 gateway via Docker on Azure. Is there some alternative way then to "listen" to bucket notifications? I'm looking to run a script on an event basis, i.e. every time a new object is uploaded to the S3 bucket.

**Comment by harshavardhana** [comment]
@MatinF `minio gateway` does not implement Listen feature other than NAS gateway
