### ISSUE TITLE
Error while providing version_id to enable_object_legal_hold

### ISSUE THREAD

**Issue by HuseynMashadiyev** [minio/minio-py#1196]
Python 3.8
Minio SDK: 7.1.7

When I execute following commands:

```python
from minio import Minio 

client =  Minio(...)

client.enable_object_legal_hold("locked", "object", '68494287-8a8a-4a00-9f5e-f5b09ca49c38')
```

I get following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".local/lib/python3.8/site-packages/minio/api.py", line 2483, in enable_object_legal_hold
    query_params["legal-hold"] = ""
TypeError: 'set' object does not support item assignment
```

I tracked error to Line #2483 in `api.py` where there is a typo. Comma should be replaced with a colon

```python
query_params = {"versionId", version_id} if version_id else {}
query_params["legal-hold"] = ""
```

**Comment by kannappanr** [comment]
typo is present in 4 more places. lines 2659, 2622 and 2509 and 2538
