### ISSUE TITLE
the admin info call using minioadmin.py is giving python error

### ISSUE THREAD

**Issue by mukhtar-inamdar** [minio/minio-py#1208]
```
#!/usr/bin/python3
# -*- coding: utf-8 -*-

from minio import MinioAdmin

mc = MinioAdmin(target='minio', binary_path='/root/.mc/mc', config_dir='/root/.mc')
info = mc.info()
print("info: " + str(info))
```
Error:
```
[Running] /usr/bin/python3 "/root/minio/minio-py/minio-admin-example1.py"
Traceback (most recent call last):
  File "/root/minio/minio-py/minio-admin-example1.py", line 14, in <module>
    info = mc.info()
  File "/usr/local/lib/python3.6/site-packages/minio/minioadmin.py", line 75, in info
    return self._run(["info", self._target])
  File "/usr/local/lib/python3.6/site-packages/minio/minioadmin.py", line 53, in _run
    text=True,
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

[Done] exited with code=1 in 0.239 seconds
```
Python version:
```
[root@ssc-vm-rhev4-2678 minio-py]# python3 --version
Python 3.6.8
```

**Comment by harshavardhana** [comment]
> Python 3.6.8

Python 3.6 is EOLed please upgrade to Python 3.7 at the minimum

**Comment by mukhtar-inamdar** [comment]
Hey @harshavardhana,
Your document 'https://github.com/minio/minio-py#readme' mentioned python 3.6 is supported.

**Comment by balamurugana** [comment]
Python 3.6 does not have `capture_output` argument in `subprocess.run()`. You would need to have `Python >= 3.7` and we will fix the doc.

**Comment by harshavardhana** [comment]
> Hey @harshavardhana, Your document 'https://github.com/minio/minio-py#readme' mentioned python 3.6 is supported.

That is beside the point, Python 3.6 is EOLed by the Python community.
