### ISSUE TITLE
Internal expection not caught properly. 

### ISSUE THREAD

**Issue by slenderq** [minio/minio-py#1250]
Hi there, getting the following exception in my logs

```Exception ignored in: <function Minio.__del__ at 0x7f96cef4fc70>
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/minio/api.py", line 155, in __del__
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 223, in clear
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/_collections.py", line 100, in clear
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 174, in <lambda>
  File "/home/vscode/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 498, in close
TypeError: catching classes that do not inherit from BaseException is not allowed
```

It seems like some exception needs to inherit BaseException?

**Comment by slenderq** [comment]
For

**Comment by slenderq** [comment]
For reference.

I'm on Python 3.10 and minio 7.1.12

**Comment by balamurugana** [comment]
`urllib3` throws an exception which is not `BaseException` i.e. not one of python's built-in exceptions. You would need to investigate why/what exception `urllib3` is throwing.  Solution can be upgrade your `urllib3` or open an issue in `urllib3` project.

**Comment by slenderq** [comment]
Ah that makes sense. Thanks!
