### ISSUE TITLE
minio.error.S3Error: S3 operation failed; code: MetadataTooLarge, message: Your metadata headers exceed the maximum allowed metadata size.

### ISSUE THREAD

**Issue by lu123321** [minio/minio-py#1265]
![image](https://user-images.githubusercontent.com/44158315/216973887-ead3fb8d-01d5-46e8-9c46-6ef36cce7b9e.png)

windows C drive and d drive each have a minio

minio user etcd

**etcd-config**
![image](https://user-images.githubusercontent.com/44158315/216974051-5f99badb-4d7a-4d8d-9c27-0d3d8ac6bf36.png)
**minio1.bat**
set MINIO_ROOT_USER=minioadmin
set MINIO_ROOT_PASSWORD=minioadmin
set MINIO_ETCD_ENDPOINTS=http://10.6.233.201:2379
set MINIO_PUBLIC_IPS=10.6.233.201
set MINIO_DOMAIN=minio.com
.\minio.exe server  --address 10.6.233.201:9000 --console-address "10.6.233.201:9090" D:/minio

**minio2.bat**
set MINIO_ROOT_USER=minioadmin
set MINIO_ROOT_PASSWORD=minioadmin
set MINIO_ETCD_ENDPOINTS=http://10.6.233.201:2379
set MINIO_PUBLIC_IPS=10.6.233.201
set MINIO_DOMAIN=minio.com
.\minio.exe server  --address 10.6.233.201:9001 --console-address "10.6.233.201:9091" C:/minio

**Comment by klauspost** [comment]
Please post the request being made.

**Comment by balamurugana** [comment]
Enable `Minio.trace_on()` and share the output.

**Comment by lu123321** [comment]
> 请发布正在提出的请求。

minioClient.fput_object('9test', '803000000212.mp4', 'D:\douyin\gif\803000000212.mp4')

**Comment by lu123321** [comment]
> Minio.trace_on()

Connected to pydev debugger (build 183.5912.18)
---------START-HTTP---------
GET /9test?location= HTTP/1.1
Host: 10.6.233.201:9001
User-Agent: MinIO (Windows; AMD64) minio-py/7.1.13
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20230207T015305Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20230207/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 400
Traceback (most recent call last):
Accept-Ranges: bytes
  File "D:\PyCharm 2018.3.5\helpers\pydev\pydevd.py", line 1741, in <module>
Content-Length: 268
    main()
Content-Type: application/xml
  File "D:\PyCharm 2018.3.5\helpers\pydev\pydevd.py", line 1735, in main
Date: Tue, 07 Feb 2023 01:53:06 GMT
    globals = debugger.run(setup['file'], None, None, is_module)
Server: MinIO
  File "D:\PyCharm 2018.3.5\helpers\pydev\pydevd.py", line 1135, in run
Vary: Origin
    pydev_imports.execfile(file, globals, locals)  # execute the script
<?xml version="1.0" encoding="UTF-8"?>
  File "D:\PyCharm 2018.3.5\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
<Error><Code>MetadataTooLarge</Code><Message>Your metadata headers exceed the maximum allowed metadata size.</Message><Resource>/9test</Resource><RequestId></RequestId><HostId>c273d214-f40c-450e-aa46-816e0f529de3</HostId></Error>
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
----------END-HTTP----------
  File "D:/localFactory/1qjk-video/src/minio_utils.py", line 155, in <module>
    minioClient.fput_object('9test', '803000000212.mp4', 'D:\douyin\大片\803000000212.mp4')
  File "C:\Users\luyaozong\AppData\Local\Programs\Python\Python38\lib\site-packages\minio\api.py", line 989, in fput_object
    return self.put_object(
  File "C:\Users\luyaozong\AppData\Local\Programs\Python\Python38\lib\site-packages\minio\api.py", line 1766, in put_object
    raise exc
  File "C:\Users\luyaozong\AppData\Local\Programs\Python\Python38\lib\site-packages\minio\api.py", line 1720, in put_object
    return self._put_object(
  File "C:\Users\luyaozong\AppData\Local\Programs\Python\Python38\lib\site-packages\minio\api.py", line 1578, in _put_object
    response = self._execute(
  File "C:\Users\luyaozong\AppData\Local\Programs\Python\Python38\lib\site-packages\minio\api.py", line 400, in _execute
    region = self._get_region(bucket_name, None)
  File "C:\Users\luyaozong\AppData\Local\Programs\Python\Python38\lib\site-packages\minio\api.py", line 467, in _get_region
    response = self._url_open(
  File "C:\Users\luyaozong\AppData\Local\Programs\Python\Python38\lib\site-packages\minio\api.py", line 386, in _url_open
    raise response_error
minio.error.S3Error: S3 operation failed; code: MetadataTooLarge, message: Your metadata headers exceed the maximum allowed metadata size., resource: /9test, request_id: , host_id: c273d214-f40c-450e-aa46-816e0f529de3

**Comment by balamurugana** [comment]
I see `GetBucketLocation` API is failing and your server is not sending proper S3 error response. I would like you to check your server why it is not S3 complaint.

**Comment by lu123321** [comment]
> 

I'm not sure how to check it
