### ISSUE TITLE
minio for python2

### ISSUE THREAD

**Issue by Sushanti99** [minio/minio-py#1268]
Installing minio for python2.7 throws errors like this
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "minio/__init__.py", line 45, in <module>
    from .api import Minio
  File "minio/api.py", line 68
    f"MinIO ({platform.system()}; {platform.machine()}) "
                                                        ^
SyntaxError: invalid syntax
```

Is there support for python2?

**Comment by balamurugana** [comment]
It is not supported
