### ISSUE TITLE
the function upload_snowball_objects doesn't work if the size of all files added is greater than 5MiB

### ISSUE THREAD

**Issue by emrocha** [minio/minio-py#1282]
When the sum of file sizes exceeds 5Mib, the function `put_object` uses **multipart**. In this case, MinIO does not respect the `Metadata "X-Amz-Meta-Snowball-Auto-Extract=true"`. It creates only the TAR file (without splitting files).

In the blog post https://blog.min.io/minio-optimizes-small-objects/ there is a example with "mc" command to send multiple files.
This example uses the argument "--disable-multipart" for the "mc" command.

```
mc mb play/mybucket
mc cp <path-to-archive>.tar play/mybucket --disable-multipart --attr "X-Amz-Meta-Snowball-Auto-Extract=true"
mc ls play/mybucket
```

**Comment by balamurugana** [comment]
Please share your python code.

**Comment by emrocha** [comment]
```python
from minio import Minio
from minio.error import S3Error
from minio.commonconfig import SnowballObject
import os

MINIO_SERVER = os.environ['MINIO_SERVER']
MINIO_ACCESS_KEY = os.environ['MINIO_ACCESS_KEY']
MINIO_SECRET_KEY = os.environ['MINIO_SECRET_KEY']
BUCKET_NAME = os.environ['BUCKET_NAME']

def main():
    client = Minio(
        MINIO_SERVER,
        access_key=MINIO_ACCESS_KEY,
        secret_key=MINIO_SECRET_KEY,
    )
    client.upload_snowball_objects(BUCKET_NAME, [
            SnowballObject("f1.bin", filename="f1.bin"),
            SnowballObject("f2.bin", filename="f2.bin"),
        ],
        staging_filename='temp.tar'
    )

if __name__ == "__main__":
    main()
```

I used the commands below to generate the files "f1.bin" and "f2.bin".

```shell
head -c 3M </dev/urandom >f1.bin
head -c 3M </dev/urandom >f1.bin
```

I installed Minio with Helm Chart Operator and Helm Chart Tenant version **v4.5.8**.

By the way, if I remove the "staging_filename" parameter, the error below occurs:

```
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    main()
  File "main.py", line 16, in main
    client.upload_snowball_objects('teste', [
  File "/opt/test_upload_snowball_objects/venv/lib/python3.8/site-packages/minio/api.py", line 2748, in upload_snowball_objects
    return self.put_object(bucket_name, object_name, fileobj,
  File "/opt/test_upload_snowball_objects/venv/lib/python3.8/site-packages/minio/api.py", line 1767, in put_object
    raise exc
  File "/opt/test_upload_snowball_objects/venv/lib/python3.8/site-packages/minio/api.py", line 1700, in put_object
    raise IOError(
OSError: stream having not enough data;expected: 5242880, got: 0 bytes
```
