### ISSUE TITLE
Calling remove_object on png file with space in file name doesnt do anything

### ISSUE THREAD

**Issue by fboerman** [minio/minio-py#1306]
I am running minio 2023-09-07T02-05-02Z and a python script with minio-py 7.1.16

I have a png file with a space in it in a bucket. I call remove_object with the correct bucket and object name and nothing happens. If I repeat the exact same situation but now the png file doesnt have a space in it, it works!

This seems like a bug to me, anybody that can help? Thanks in advance!

**Comment by balamurugana** [comment]
It works!
```py
>>> from minio import Minio
>>> client = Minio(
    "play.min.io",
    access_key="Q3AM3UQ867SPQQA43P2F",
    secret_key="zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG",
)
... ... ... ... >>> 
>>> client.fput_object("mybucket", "hello world .png", "hello world .png")
<minio.helpers.ObjectWriteResult object at 0x7f9a44df6f50>
>>> print(client.stat_object("mybucket", "hello world .png"))
<minio.datatypes.Object object at 0x7f9a43bc1a50>
>>> client.remove_object("mybucket", "hello world .png")
>>> print(client.stat_object("mybucket", "hello world .png"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bala/devel/github.com/minio/minio-py/minio/api.py", line 1862, in stat_object
    response = self._execute(
               ^^^^^^^^^^^^^^
  File "/home/bala/devel/github.com/minio/minio-py/minio/api.py", line 408, in _execute
    return self._url_open(
           ^^^^^^^^^^^^^^^
  File "/home/bala/devel/github.com/minio/minio-py/minio/api.py", line 391, in _url_open
    raise response_error
minio.error.S3Error: S3 operation failed; code: NoSuchKey, message: Object does not exist, resource: /mybucket/hello%20world%20.png, request_id: 1784024421B521B7, host_id: 3e996b2f640d7e065d3a5c4e39a5538cefb82e3e77771990265e4698d8681eac, bucket_name: mybucket, object_name: hello world .png
>>> 
```

May be you would need to upgrade your server or open an issue with minio server.
