### ISSUE TITLE
set_bucket_tags() - S3 operation failed; code: MalformedBucketLabelsRequest

### ISSUE THREAD

**Issue by djk2** [minio/minio-py#1388]
Hi. 

I try to add tags to bucket on GCP. 
My code is

```
from minio import Minio
from minio.commonconfig import Tags

client = Minio(...)
tags = Tags.new_bucket_tags()
tags["app"] = "Test"

client.set_bucket_tags("name_of_bucket", tags)
```

Unfortunately I get error: 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/xxx/lib/python3.10/site-packages/minio/api.py", line 2414, in set_bucket_tags
    self._execute(
  File "xxx/lib/python3.10/site-packages/minio/api.py", line 421, in _execute
    return self._url_open(
  File "xxx/lib/python3.10/site-packages/minio/api.py", line 404, in _url_open
    raise response_error
minio.error.S3Error: S3 operation failed; code: MalformedBucketLabelsRequest, message: The bucket labels request XML you provided was not well-formed or did not validate against our published schema., resource: None, request_id: None, host_id: None
```

Python 3.10.12
Miino 7.2.3 and 7.1.17
Description: Ubuntu 22.04.3 LTS
I'm using virtual env by pipenv

I will be regard for help.

**Comment by balamurugana** [comment]
`minio-py` supports S3 object storage only
