### ISSUE TITLE
Unicode decode error on python put_object.py

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-py#142]
~~~
$ python put_object.py 
Traceback (most recent call last):
  File "put_object.py", line 27, in <module>
    client.put_object('ferenginar', 'my_key', file_stat.st_size, file_data)
  File "/usr/local/lib/python2.7/dist-packages/minio/minio.py", line 374, in put_object
    self._stream_put_object(bucket, key, length, data, content_type)
  File "/usr/local/lib/python2.7/dist-packages/minio/minio.py", line 555, in _stream_put_object
    current_data_md5 = convert_binary_to_hex(get_md5(current_data))
  File "/usr/local/lib/python2.7/dist-packages/minio/helpers.py", line 76, in get_md5
    content = content.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xab in position 24: ordinal not in range(128)
~~~

put_object.py
~~~
import os

from minio import Minio

__author__ = 'minio'

client = Minio('https://s3.amazonaws.com',
               access_key='*redacted*',
               secret_key='*redacted*')

# Put a file
file_stat = os.stat('/usr/bin/pandoc')
with open('/usr/bin/pandoc', 'rb') as file_data:
    client.put_object('ferenginar', 'my_key', file_stat.st_size, file_data)
~~~

**Comment by fkautz** [comment]
Removed section of code causing problems in minio library, but this uncovered the same issue within python's standard httplib.

Going to further investigate how we can get python to treat a binary "string" as a binary. Adding the stack trace here for further info.

```py
Traceback (most recent call last):
  File "/home/fkautz/src/minio-py/integration/put_object_integration.py", line 71, in put_binary_object_test
    client.put_object(bucket, 'binary_object', file_stat.st_size, data_file)
  File "/home/fkautz/src/minio-py/minio/minio.py", line 375, in put_object
    return self._do_put_object(bucket, key, length, data, content_type)
  File "/home/fkautz/src/minio-py/minio/minio.py", line 521, in _do_put_object
    response = self._http.urlopen(method, url, headers=headers, body=data)
  File "/home/fkautz/.local/lib/python2.7/site-packages/urllib3/poolmanager.py", line 161, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/fkautz/.local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/home/fkautz/.local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1048, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1088, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1044, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 886, in _send_output
    msg += message_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 24: ordinal not in range(128)
```
