### ISSUE TITLE
A statObject will not have a parseable error body, so we might get frivolous parse error exceptions - need to handle it

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-py#151]
~~~
======================================================================
ERROR: test_object_not_found (tests.integration.stat_object_integration.StatObjectIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/tools/nontrivial.py", line 60, in newfunc
    func(*arg, **kw)
  File "/home/harsha/repos/minio-py/tests/integration/stat_object_integration.py", line 48, in test_object_not_found
    result = client.stat_object(bucket, 'missing-object')
  File "/home/harsha/repos/minio-py/minio/minio.py", line 438, in stat_object
    parse_error(response)
  File "/home/harsha/repos/minio-py/minio/parsers.py", line 180, in parse_error
    root = ElementTree.fromstring(response.content)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    return parser.close()
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1654, in close
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: no element found: line 1, column 0
~~~

**Comment by fkautz** [comment]
Should be fixed in latest version.

**Comment by abperiasamy** [comment]
We should keep such issues open until they are fixed.

**Comment by harshavardhana** [comment]
~~~
$ nosetests -s integration/stat_object_integration.py 
.EE
======================================================================
ERROR: test_object_not_found (integration.stat_object_integration.StatObjectIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/tools/nontrivial.py", line 60, in newfunc
    func(*arg, **kw)
  File "/home/harsha/repos/minio-py/integration/stat_object_integration.py", line 48, in test_object_not_found
    result = client.stat_object(bucket, 'missing-object')
  File "/home/harsha/repos/minio-py/minio/minio.py", line 441, in stat_object
    parse_error(response)
  File "/home/harsha/repos/minio-py/minio/parsers.py", line 180, in parse_error
    root = ElementTree.fromstring(response.data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    return parser.close()
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1654, in close
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: no element found: line 1, column 0
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: DEBUG: "HEAD /goroutine-py/missing-object HTTP/1.1" 301 0
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_stat_object_works (integration.stat_object_integration.StatObjectIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/harsha/repos/minio-py/integration/stat_object_integration.py", line 37, in test_stat_object_works
    result = client.stat_object(bucket, 'hello')
  File "/home/harsha/repos/minio-py/minio/minio.py", line 441, in stat_object
    parse_error(response)
  File "/home/harsha/repos/minio-py/minio/parsers.py", line 180, in parse_error
    root = ElementTree.fromstring(response.data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    return parser.close()
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1654, in close
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: no element found: line 1, column 0
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: DEBUG: "HEAD /goroutine-py/hello HTTP/1.1" 301 0
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 3 tests in 0.221s

FAILED (errors=2)
~~~

The issue here is if you have no access keys specified.. for StatObject, StatBucket there is no response body.

Upon errors only headers are available so a parseError on the body is bound to throw exception, in this scenario due to lack of credentials. 

~~~
$ cat ~/credentials.json
{
  "host": "https://s3.amazonaws.com"
}
~~~

**Comment by harshavardhana** [comment]
For example for a put_object() operation a proper ResponseError is available so no XML parsing issues. 

~~~
======================================================================
ERROR: put_small_object_test (integration.put_object_integration.PutObjectIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/harsha/repos/minio-py/integration/put_object_integration.py", line 35, in put_small_object_test
    client.put_object(bucket, 'small_obj', 11, 'hello world', content_type='text/plain')
  File "/home/harsha/repos/minio-py/minio/minio.py", line 375, in put_object
    return self._do_put_object(bucket, key, length, data, content_type)
  File "/home/harsha/repos/minio-py/minio/minio.py", line 524, in _do_put_object
    parse_error(response)
  File "/home/harsha/repos/minio-py/minio/parsers.py", line 193, in parse_error
    raise ResponseError(code, message, request_id, host_id, resource)
ResponseError: 
-------------------- >> begin captured logging << --------------------
urllib3.connectionpool: INFO: Resetting dropped connection: s3.amazonaws.com
urllib3.connectionpool: DEBUG: "PUT /goroutine-py/small_obj HTTP/1.1" 301 None
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 5 tests in 2.544s

FAILED (errors=5)
~~~

**Comment by fkautz** [comment]
Expanded the types of errors covered when a 0 length data response is provided. Should cover any error response now.
