### ISSUE TITLE
Object keys should be url encoded

### ISSUE THREAD

**Issue by fkautz** [minio/minio-py#173]
put a file with a ? or # in the name results in unexpected truncation of the key

```py
client.put_object(bucket, 'test/a?directory', 11, 'hello world')
str(client.stat_object(bucket, 'test/a'))
```

**Comment by fkautz** [comment]
```py
>>> client.put_object(bucket, 'encoding/世界', 11, 'hello world')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "minio/minio.py", line 386, in put_object
    return self._do_put_object(bucket, key, length, data, content_type)
  File "minio/minio.py", line 530, in _do_put_object
    secret_key=self._secret_key, content_hash=content_sha256)
  File "minio/signer.py", line 51, in sign_v4
    canonical_request_hasher.update(canonical_request.encode('utf-8'))
```
