### ISSUE TITLE
Non-recursive list objects paging fails when the page falls on an encoded string

### ISSUE THREAD

**Issue by fkautz** [minio/minio-py#198]
We only see this behavior when recursive = False

```py
<Object: bucket: goroutine-testpy key: encoding/世界 last_modified: 2015-07-09 18:31:01+00:00 etag: 5eb63bbbe01eeed093cb22bb8f5acdc3 size: 11 content_type: None>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fkautz/.local/lib/python2.7/site-packages/minio/generators.py", line 41, in next
    return self.__next__()
  File "/home/fkautz/.local/lib/python2.7/site-packages/minio/generators.py", line 53, in __next__
    self._results, self._is_truncated, self._marker = self._fetch()
  File "/home/fkautz/.local/lib/python2.7/site-packages/minio/generators.py", line 71, in _fetch
    url = get_target_url(self._scheme, self._location, bucket=self._bucket, query=query)
  File "/home/fkautz/.local/lib/python2.7/site-packages/minio/helpers.py", line 41, in get_target_url
    single_component.append(compat_pathname2url(cgi.escape(str(ordered_query[component_key]))).replace('/', '%2F'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-10: ordinal not in range(128)
```

**Comment by fkautz** [comment]
Fixed by #202
