### ISSUE TITLE
Looks like "localhost:9000" port gets stripped off when adding to "host" in signer

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-py#206]
$ python put_object.py 
~~~
GET
/ferenginar
prefix=my_key&uploads=
host:localhost
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20150710T033928Z

host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
['host', 'x-amz-content-sha256', 'x-amz-date']
Traceback (most recent call last):
  File "put_object.py", line 27, in <module>
    client.put_object('ferenginar', 'my_key', file_stat.st_size, file_data)
  File "/home/harsha/repos/minio-py/minio/minio.py", line 400, in put_object
    self._stream_put_object(bucket, key, length, data, content_type)
  File "/home/harsha/repos/minio-py/minio/minio.py", line 576, in _stream_put_object
    for upload in current_uploads:
  File "/home/harsha/repos/minio-py/minio/generators.py", line 107, in next
    return self.__next__()
  File "/home/harsha/repos/minio-py/minio/generators.py", line 119, in __next__
    self._results, self._is_truncated, self._key_marker, self._upload_id_marker = self._fetch()
  File "/home/harsha/repos/minio-py/minio/generators.py", line 155, in _fetch
    parse_error(response)
  File "/home/harsha/repos/minio-py/minio/parsers.py", line 208, in parse_error
    raise ResponseError(code, message, request_id, host_id, resource, response.data)
minio.parsers.ResponseError: ResponseError: code: InternalError, message: We encountered an internal error, please try again., request_id: 3L137, host_id: 3L137, resource: /ferenginar, xml: <Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Resource>/ferenginar</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
~~~

**Comment by fkautz** [comment]
Should be fixed with #207. Can you try again?
