### ISSUE TITLE
Error running example with  minio-py

### ISSUE THREAD

**Issue by koolhead17** [minio/minio-py#284]
I am trying to test minio-py on ubuntu

$ sudo pip install minio

After that i am trying to list all my buckets: with my secret/access key

```
#!/usr/bin/env python

from minio.minio import Minio

# Instantiate a client
client = Minio('https://s3.amazonaws.com',
                access_key='MYKey',
                secret_key='MYKey')

# List buckets
buckets = client.list_buckets()
for bucket in buckets:
    print 'bucket:', bucket.name, bucket.creation_date

I am getting this error:

ubuntu@ubuntu:~/python$ python listB.py

▽
Traceback (most recent call last):
  File "listB.py", line 11, in <module>
    buckets = client.list_buckets()
  File "/usr/local/lib/python2.7/dist-packages/minio/minio.py", line 186, in list_buckets
    redirect=False)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 75, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 88, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 155, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 595, in urlopen
    raise SSLError(e)
urllib3.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

**Comment by krishnasrinivas** [comment]
can you change this line `from minio.minio import Minio` to `from minio import Minio`

**Comment by harshavardhana** [comment]
```
>>> http = urllib3.PoolManager(
...             cert_reqs='CERT_REQUIRED',
...             ca_certs=certs
...         )
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
NameError: name 'certs' is not defined
>>> import certifi
>>> certs = certifi.where()
>>> print certs
/usr/local/lib/python2.7/dist-packages/certifi/cacert.pem
>>> urllib3.PoolManager(
...             cert_reqs='CERT_REQUIRED',
...             ca_certs=certs
...         )
<urllib3.poolmanager.PoolManager object at 0x7f79efd2acd0>
>>> http = urllib3.PoolManager(
...             cert_reqs='CERT_REQUIRED',
...             ca_certs=certs
...         )
>>> http.request('GET', 'https://www.google.com/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 75, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 88, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 155, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 595, in urlopen
    raise SSLError(e)
urllib3.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
>>> http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED')
>>> http.request('GET', 'https://www.google.com/')
<urllib3.response.HTTPResponse object at 0x7f79efd2a750>
>>> http.request('GET', 'https://www.google.com/').status
200
>>> http.request('GET', 'https://s3.amazonaws.com').status
200
>>> http.request('GET', 'https://play.minio.io:9000').status
200
>>> http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED', certs=certs)
>>> http.request('GET', 'https://play.minio.io:9000').status
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 75, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 88, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 145, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 119, in connection_from_host
    pool = self._new_pool(scheme, host, port)
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 86, in _new_pool
    return pool_cls(host, port, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'certs'
>>> http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED', ca_erts=certs)
>>> http = urllib3.PoolManager(cert_reqs='CERT_REQUIRED', ca_certs=certs)
>>> http.request('GET', 'https://play.minio.io:9000').status
200
>>> http.request('GET', 'https://google.com').status
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 75, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 88, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 155, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 595, in urlopen
    raise SSLError(e)
urllib3.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
>>> http.request('GET', 'https://s3.amazonaws.com').status
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 75, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 88, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 155, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 595, in urlopen
    raise SSLError(e)
urllib3.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
>>> http.request('GET', 'https://dl.minio.io:9000').status
403
>>> http.request('GET', 'https://dl.minio.io:9000/updates').status
200
>>> http.request('GET', 'https://minio.io').status
200
>>> http.request('GET', 'https://github.com').status
200
>>> http.request('GET', 'https://atuljha.com').status
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 75, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 88, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 155, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 595, in urlopen
    raise SSLError(e)
  File "<stdin>", line 1, in <module>
urllib3.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate v
erify failed
>>> http.request('GET', 'https://ndtv.com').status
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 75, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 88, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 155, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 628, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 628, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 628, in urlopen
    release_conn=release_conn, **response_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 612, in urlopen
    raise MaxRetryError(self, url, e)
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ndtv.com', port=443): Max retries exceeded with url: / (Caus
ed by <class 'socket.error'>: [Errno 111] Connection refused)
>>> http.request('GET', 'https://bankofamerica.com').status
200
>>> http.request('GET', 'https://wellsfargo.com').status
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 75, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 88, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 155, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 595, in urlopen
    raise SSLError(e)
urllib3.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate v
erify failed
>>> http.request('GET', 'https://slack.com').status
200
>>> http.request('GET', 'https://gitter.im').status
200
>>> 
```

**Comment by harshavardhana** [comment]
The problem is in the certifi package which works for many domains and does not work for as simple as google.com - i guess removing the dependency will fix the problem.

**Comment by harshavardhana** [comment]
Relevant issues 

- https://github.com/aws/aws-cli/issues/1499
- https://github.com/certifi/python-certifi/issues/26

**Comment by koolhead17** [comment]
Closing this as upgrading minio package will  fix issue.
