### ISSUE TITLE
conn.bucket_exists() raises an error if the bucket does not exist

### ISSUE THREAD

**Issue by bacongobbler** [minio/minio-py#352]
The expected result was for the function to return False.

Usage:

```
#!/usr/bin/env python

import os
import sys
from minio import Minio


conn = Minio(
    "{}:{}".format(
        os.getenv('MINIO_HOST'),
        os.getenv('MINIO_PORT')),
    access_key=os.getenv('AWS_ACCESS_KEY_ID'),
    secret_key=os.getenv('AWS_SECRET_ACCESS_KEY'),
    insecure=True)
name = sys.argv[1]

if not conn.bucket_exists(name):
    conn.make_bucket(name)
```

Result:

```
Traceback (most recent call last):
  File "/bin/create_bucket", line 17, in <module>
    if not conn.bucket_exists(name):
  File "/usr/local/lib/python2.7/dist-packages/minio/api.py", line 288, in bucket_exists
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/minio/api.py", line 1546, in _url_open
    raise response_error.head(bucket_name, object_name)
minio.error.ResponseError: ResponseError: code: NoSuchBucket, message: Not Found, bucket_name: dbwal, object_name: None, request_id: B18FMJCFUCGD0T3E, host_id: , region:
```

**Comment by harshavardhana** [comment]
Agreed :+1:
