### ISSUE TITLE
CopyObject API not properly raising InvalidArgumentErr exception

### ISSUE THREAD

**Issue by muminoff** [minio/minio-py#411]
@harshavardhana Thanks for `CopyObject` API, I really needed it these days. But after I started to play around with it, I experienced following issue.

When no passing `CopyConditions()` to `mc.copy_object(..)`, `InvalidArgumentErr` exception is not being raised properly.

Example code:
```python
>>> mc.copy_object('l1wpmwx4-deleted', 'l1wpmwx4/qizaloq.mp4', 'qizaloq.mp4')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    mc.copy_object('l1wpmwx4-deleted', 'l1wpmwx4/qizaloq.mp4', 'qizaloq.mp4')
  File "/Users/sardor/.virtualenvs/floppy/lib/python3.5/site-packages/minio/api.py", line 789, in copy_object
    raise InvalidArgumentErr('Input conditions should be of type '
NameError: name 'InvalidArgumentErr' is not defined
```

Python version
```bash
$ python --version
Python 3.5.2
```

minio-py version
```python
>>> import minio
>>> minio.__version__
'2.0.2'
```

minio version
```bash
$ minio version
Version: 2016-09-11T17:42:18Z
Release-Tag: RELEASE.2016-09-11T17-42-18Z
Commit-ID: 85e2d886bcb005d49f3876d6849a2b5a55e03cd3
```

Thanks in advance.

**Comment by muminoff** [comment]
Related to #406
