### ISSUE TITLE
get_policy crashes with minio server

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-py#422]
```
Traceback (most recent call last):
  File "tests.py", line 188, in <module>
    main()
  File "tests.py", line 162, in main
    policy_name = client.get_bucket_policy(bucket_name)
  File "/home/harsha/repos/minio-py/minio/api.py", line 341, in get_bucket_policy
    return policy.get_policy(statements, bucket_name, prefix)
  File "/home/harsha/repos/minio-py/minio/policy.py", line 463, in get_policy
    fnmatch.fnmatch(object_resource, resource)):
  File "/usr/lib/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/usr/lib/python2.7/fnmatch.py", line 77, in fnmatchcase
    re_pat = _cache[pat]
TypeError: unhashable type: 'list'
```

**Comment by GarimaKapoor** [comment]
@krisis what is the status on this issue. Do we have a timeline for the fix?

**Comment by balamurugana** [comment]
Policy implementation can be improved by referring minio-java and minio-go code.  They have improved version of policy management.

**Comment by krisis** [comment]
@GarimaKapoor I am currently working on minio server related issues which take precedence over this. I am not working on this issue now.

**Comment by harshavardhana** [comment]
Unassigned @krisis

**Comment by ChillarAnand** [comment]
This is happening because of new policy. Similar to https://github.com/minio/minio-py/issues/448
