### ISSUE TITLE
set_bucket_policy doesn't work

### ISSUE THREAD

**Issue by ChillarAnand** [minio/minio-py#448]
In the examples, it is mentioned that [this should work](https://github.com/minio/minio-py/blob/eaca7a4279471151126e4b4dd3eaa5880550b7d5/examples/set_bucket_policy.py#L32):

    client.set_bucket_policy('my-bucketname', '', Policy.READ_ONLY)

I tried this on local system but it throws error
```py
import minio

mc = minio.Minio(
    endpoint='0.0.0.0:9000',
    access_key='foo',
    secret_key='1l+E',
    secure=False,
)

mc.set_bucket_policy('test-public', '', minio.policy.Policy.READ_ONLY)
```

```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chillaranand/.01/python/minio_exp.py", line 12, in <module>
    mc.set_bucket_policy('mycroft-public', '', minio.policy.Policy.READ_ONLY)
  File "/home/chillaranand/.virtualenvs/sherlock/lib/python3.5/site-packages/minio/api.py", line 369, in set_bucket_policy
    bucket_name, prefix)
  File "/home/chillaranand/.virtualenvs/sherlock/lib/python3.5/site-packages/minio/policy.py", line 496, in set_policy
    bucket_name, prefix)
  File "/home/chillaranand/.virtualenvs/sherlock/lib/python3.5/site-packages/minio/policy.py", line 236, in _remove_statements
    in_use = _get_in_use_policy(statements, bucket_name, prefix)
  File "/home/chillaranand/.virtualenvs/sherlock/lib/python3.5/site-packages/minio/policy.py", line 135, in _get_in_use_policy
    resource.startswith(resource_prefix)):
AttributeError: 'list' object has no attribute 'startswith'
```

But the same works with `mc`

    → mc policy download local/mycroft-public
    Access permission for ‘local/mycroft-public’ is set to ‘download’

**Comment by harshavardhana** [comment]
Fixed by #449
