### ISSUE TITLE
list_objects not working, got AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by ryanho** [minio/minio-py#462]
minio ver: 2017-01-25T03:14:52Z
Python 3.5.2
minio-py: 2.0.6

```
>>> objects = minioClient.list_objects("test", '', True)
>>> for obj in objects:
...     print(obj.bucket_name, obj.object_name.encode('utf-8'), obj.last_modified,
...           obj.etag, obj.size, obj.content_type)
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ryan/Envs/mangamanager/lib/python3.5/site-packages/minio/api.py", line 882, in list_objects
    bucket_name=bucket_name)
  File "/home/ryan/Envs/mangamanager/lib/python3.5/site-packages/minio/parsers.py", line 235, in parse_list_objects
    root.findall('CommonPrefixes')
  File "/home/ryan/Envs/mangamanager/lib/python3.5/site-packages/minio/parsers.py", line 204, in _parse_objects_from_xml_elts
    for content in contents
  File "/home/ryan/Envs/mangamanager/lib/python3.5/site-packages/minio/parsers.py", line 204, in <listcomp>
    for content in contents
  File "/home/ryan/Envs/mangamanager/lib/python3.5/site-packages/minio/parsers.py", line 126, in get_etag_elem
    return self.get_child_text('ETag').replace('"', '')
AttributeError: 'NoneType' object has no attribute 'replace'

```

**Comment by harshavardhana** [comment]
This is fixed in the latest release 2.0.7 - closing.
