### ISSUE TITLE
TypeError when listing top-level objects

### ISSUE THREAD

**Issue by akheron** [minio/minio-py#464]
I have a bucket "test" with one object: `foo/bar.txt`. Note that there are no objects on the top level of the bucket, only in a subdirectory.

Issuing `list_objects('test', prefix='', recursive=False)` causes the following exception:

```
>>> list(client.list_objects('test', prefix='', recursive=False))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/minio/api.py", line 882, in list_objects
    bucket_name=bucket_name)
  File "/usr/local/lib/python3.4/site-packages/minio/parsers.py", line 235, in parse_list_objects
    root.findall('CommonPrefixes')
  File "/usr/local/lib/python3.4/site-packages/minio/parsers.py", line 210, in _parse_objects_from_xml_elts
    for dirs_elt in common_prefixes
  File "/usr/local/lib/python3.4/site-packages/minio/parsers.py", line 211, in <listcomp>
    for dir_elt in dirs_elt
TypeError: 'S3Element' object is not iterable
```

The same happens with `list_objects_v2`:
```
>>> list(client.list_objects_v2('test', prefix='', recursive=False))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/minio/api.py", line 947, in list_objects_v2
    response.data, bucket_name=bucket_name
  File "/usr/local/lib/python3.4/site-packages/minio/parsers.py", line 264, in parse_list_objects_v2
    root.findall('CommonPrefixes')
  File "/usr/local/lib/python3.4/site-packages/minio/parsers.py", line 210, in _parse_objects_from_xml_elts
    for dirs_elt in common_prefixes
  File "/usr/local/lib/python3.4/site-packages/minio/parsers.py", line 211, in <listcomp>
    for dir_elt in dirs_elt
TypeError: 'S3Element' object is not iterable
```

**Comment by donatello** [comment]
Acknowledge the bug. Working on a fix.
