### ISSUE TITLE
In python3, an error happened - can only concatenate list (not "str") to list 

### ISSUE THREAD

**Issue by museghost** [minio/minio-py#479]
Dear team

I am a fan of this project minio.io and its client libraries.
When I try to use "set_bucket_policy" function in python 3.5, the following is occurred.
Also, I use the latest committed version from this github.

my code is...
```python
mc = Minio(xxxxxx)
mc.set_bucket_policy(self.bucket_name, '', Policy.READ_WRITE)
```

```python
======================================================================
ERROR: test_01_get_bucket (test_minio_uploader.BSUploaderTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tests/test_minio_uploader.py", line 27, in test_01_get_bucket
   mc.set_bucket_policy(self.bucket_name, '', Policy.READ_WRITE)
  File "/venv/bsbizpy/lib/python3.5/site-packages/minio/api.py", line 385, in set_bucket_policy
    bucket_name, prefix)
  File "/venv/bsbizpy/lib/python3.5/site-packages/minio/policy.py", line 567, in set_policy
    bucket_name, prefix)
  File "/venv/bsbizpy/lib/python3.5/site-packages/minio/policy.py", line 325, in _remove_statements
    for v in values]
  File "/venv/bsbizpy/lib/python3.5/site-packages/minio/policy.py", line 325, in <listcomp>
    for v in values]
TypeError: can only concatenate list (not "str") to list
```

My suspection is the "bucket_resource", since bucket_resource type is list, not str as below.

bucket_resource: ['arn:aws:s3:::testbucket']/<class 'list'>

I think that bucket_resource[0] might be applied to get the s3_prefix_value.

```python
 values = string_equals_value.get('s3:prefix', [])
                if isinstance(values, basestring):
                    values = [values]

                s3_prefix_value += [(bucket_resource + '/' + v + '*')
                                    for v in values]
```

If possible, could you please look at this and make a patch for us ?

Best Regards
Thanks

**Comment by harshavardhana** [comment]
Will take a look @museghost
