### ISSUE TITLE
list bucket doesnt work on python 3.6

### ISSUE THREAD

**Issue by jtoy** [minio/minio-py#553]
python -V
Python 3.6.0 :: Anaconda 4.3.1 (64-bit)
running some of the examples dont work:
import os
from minio import Minio
from minio.error import ResponseError
s3client = Minio('s3.amazonaws.com', access_key=os.environ.get('AWS_ACCESS_KEY_ID'),secret_key=os.environ.get('AWS_SECRET_ACCESS_KEY'))
buckets = s3client.list_buckets()

for bucket in buckets:
  print(bucket.name, bucket.creation_date)

    python mim.py
Traceback (most recent call last):
  File "/home/jtoy/anaconda3/lib/python3.6/site-packages/minio/parsers.py", line 72, in fromstring
    return cls(root_name, cElementTree.fromstring(data))
  File "/home/jtoy/anaconda3/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: undefined entity: line 163, column 100

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mim.py", line 5, in <module>
    buckets = s3client.list_buckets()
  File "/home/jtoy/anaconda3/lib/python3.6/site-packages/minio/api.py", line 300, in list_buckets
    return parse_list_buckets(response.data)
  File "/home/jtoy/anaconda3/lib/python3.6/site-packages/minio/parsers.py", line 185, in parse_list_buckets
    root = S3Element.fromstring('ListBucketsResult', data)
  File "/home/jtoy/anaconda3/lib/python3.6/site-packages/minio/parsers.py", line 76, in fromstring
    root_name, error.message
minio.error.InvalidXMLError: InvalidXMLError: message: "ListBucketsResult" XML is not parsable. Message: undefined entity: line 163, column 100

**Comment by vadmeste** [comment]
@jtoy, I have the same error message if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are not set in the environment, otherwise it works fine.

Can you check again if access and secret keys are really set ?

**Comment by jtoy** [comment]
yeah it was the keys not being set.  I thought that  the connection call will check the keys. thanks!

**Comment by harshavardhana** [comment]
We will need to throw an error for ListBuckets by caching the parsing failure here @vadmeste

**Comment by harshavardhana** [comment]
Reopening so that we fix this with a proper error exception.

**Comment by jtoy** [comment]
Agreed , there should be an error on bad credentials.
