### ISSUE TITLE
Python 3.6.x and 'tuple' object is not callable

### ISSUE THREAD

**Issue by playfullcats** [minio/minio-py#653]
There is a problem with Python 3.6.x (tested on 3.6.2, 3.6.5), minio-py3 1.0.1.1 and this code:

```
from minio import Minio

minioClient = Minio(
    '127.0.0.1:9999',
    access_key='x',
    secret_key='x',
    secure=False
)

minioClient.bucket_exists("test")
```
Always getting error on any method call:
```
Traceback (most recent call last):
  File "/home/test/projects/scripts/test/miniotest.py", line 5, in <module>
    minioClient.bucket_exists("test")
  File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 280, in bucket_exists
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 1475, in _url_open
    region = self._get_bucket_region(bucket_name)
  File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 1421, in _get_bucket_region
    region = self._get_bucket_location(bucket_name)
  File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 1445, in _get_bucket_location
    self._secret_key, None)
  File "/usr/local/lib/python3.6/site-packages/minio/signer.py", line 208, in sign_v4
    content_sha256.decode('ascii'))
  File "/usr/local/lib/python3.6/site-packages/minio/signer.py", line 234, in generate_canonical_request
    content_sha256 = str(content_sha256)
TypeError: 'tuple' object is not callable
```
But it works without error with Python 3.5.2.

**Comment by harshavardhana** [comment]
@playfullcats @mktums is right - thanks. `pip install minio` is the official package not `minio-py3`

**Comment by kannappanr** [comment]
@playfullcats Closing this issue as answered.
