### ISSUE TITLE
Can't set bucket policy

### ISSUE THREAD

**Issue by alejandroandreu** [minio/minio-py#681]
Hi all,

I have this simple script to upload a given file to my local Minio instance. Upon creating the bucket that I need, I try to set a read-only-to-all policy. I've seen this traceback before when calling `hashlib` library before, and it looks like it might be something related to it, as the helper class `Hasher` in `helpers.py` makes use of it. Any ideas?

**Script**
```import argparse
# Import Minio library.
from minio import Minio
from minio.error import (ResponseError, BucketAlreadyOwnedByYou,
                         BucketAlreadyExists)
from os import path

parser = argparse.ArgumentParser()
parser.add_argument("file")
args = parser.parse_args()
file = args.file

print("%%% Uploading file {}".format(file))

# Initialize minioClient with an endpoint and access/secret keys.
minioClient = Minio('127.0.0.1:9000',
                    access_key='LZC9H1KOIG1VGV1O76CR',
                    secret_key='bFHvAIesHdeLPckZfS73tXjRuoKIkqDvWsCFuvnG',
                    secure=False)

# Make a bucket with the make_bucket API call.
try:
       minioClient.make_bucket("mybucket", location="us-east-1")
except BucketAlreadyOwnedByYou as err:
       pass
except BucketAlreadyExists as err:
       pass
except ResponseError as err:
       raise

policy_read_only = {"Version": "2012-10-17",
                            "Statement": [
                                {
                                    "Sid": "",
                                    "Effect": "Allow",
                                    "Principal": {"AWS": "*"},
                                    "Action": "s3:GetBucketLocation",
                                    "Resource": "arn:aws:s3:::mybucket"
                                },
                                {
                                    "Sid": "",
                                    "Effect": "Allow",
                                    "Principal": {"AWS": "*"},
                                    "Action": "s3:ListBucket",
                                    "Resource": "arn:aws:s3:::mybucket"
                                },
                                {
                                    "Sid": "",
                                    "Effect": "Allow",
                                    "Principal": {"AWS": "*"},
                                    "Action": "s3:GetObject",
                                    "Resource": "arn:aws:s3:::mybucket/*"
                                }
                            ]}
minioClient.set_bucket_policy('mybucket', policy_read_only)

try:
       minioClient.fput_object('mybucket', path.basename(file), file)
except ResponseError as err:
       print(err))
```

**Traceback**
```
%%% Uploading file /tmp/.touchpaddefaults
Traceback (most recent call last):
  File "DONOTCOMMIT/tests/uploader.py", line 55, in <module>
    minioClient.set_bucket_policy('mybucket', policy_read_only)
  File "/home/alejandro/.local/lib/python3.5/site-packages/minio/api.py", line 390, in set_bucket_policy
    'Content-Md5': get_md5_base64digest(policy)
  File "/home/alejandro/.local/lib/python3.5/site-packages/minio/helpers.py", line 577, in get_md5_base64digest
    return Hasher.md5(content).base64digest()
  File "/home/alejandro/.local/lib/python3.5/site-packages/minio/helpers.py", line 535, in md5
    return cls(data, hashlib.md5)
  File "/home/alejandro/.local/lib/python3.5/site-packages/minio/helpers.py", line 531, in __init__
    self.h = h(data)
TypeError: object supporting the buffer API required
```

**Comment by harshavardhana** [comment]
> minioClient.set_bucket_policy('mybucket', policy_read_only)

Looks like you are on Python 3.x ?? Would you mind adding `b`

> policy_read_only = {"Version": "2012-10-17",

To 

> policy_read_only = b'{"Version": "2012-10-17",....

**Comment by alejandroandreu** [comment]
Thanks for the quick response, that seems to do the trick :+1: Is this something that will be addressed in the future? And if so, how? My uninformed guess from the user's point of view is that the library should handle the situation in one of these ways:

- Print a meaningful warning when attempting to pass a regular string from Python 3.x and also warn users [in the docs](https://docs.minio.io/docs/python-client-api-reference#set_bucket_policy)
- Modify the code so this conversion to a string literal is done at the library level when Python 3.x is benig used (so the docs don't have to be changed)

**Comment by harshavardhana** [comment]
> Thanks for the quick response, that seems to do the trick  Is this something that will be addressed in the future? And if so, how? My uninformed guess from the user's point of view is that the library should handle the situation in one of these ways:
> 
> Print a meaningful warning when attempting to pass a regular string from Python 3.x and also warn users in the docs
> Modify the code so this conversion to a string literal is done at the library level when Python 3.x is benig used (so the docs don't have to be changed)

We need to handle it properly ourselves and we will fix it thanks for confirming that it works, please open a GitHub issue at https://github.com/minio/minio-py/issues

**Comment by alejandroandreu** [comment]
Yet another one? You mean a more technical one?

**Comment by harshavardhana** [comment]
> Yet another one? You mean a more technical one?

Oops, I was confused nevermind - i thought this issue is on `minio/minio` repository.

**Comment by alejandroandreu** [comment]
I guess it's equivalent because in Python 3 and as far as I know, strings are encoded in UTF-8 by default but... This is what did the trick for me, I forgot to say yesterday :sweat_smile: No need to specify the `b` before defining the string bucket policy variable.

```
policy_read_only = '''{"Version": "2012-10-17",
                            "Statement": [
                                {
                                    "Sid": "",
                                    "Effect": "Allow",
                                    "Principal": {"AWS": "*"},
                                    "Action": "s3:GetBucketLocation",
                                    "Resource": "arn:aws:s3:::damnbucket"
                                },
                                {
                                    "Sid": "",
                                    "Effect": "Allow",
                                    "Principal": {"AWS": "*"},
                                    "Action": "s3:ListBucket",
                                    "Resource": "arn:aws:s3:::damnbucket"
                                },
                                {
                                    "Sid": "",
                                    "Effect": "Allow",
                                    "Principal": {"AWS": "*"},
                                    "Action": "s3:GetObject",
                                    "Resource": "arn:aws:s3:::damnbucket/*"
                                }
                            ]}'''
minioClient.set_bucket_policy('damnbucket', policy_read_only)```
