### ISSUE TITLE
get_bucket_notification example throws minio.error.InvalidXMLError

### ISSUE THREAD

**Issue by bdenglish** [minio/minio-py#696]
using the play.minio.io server and the examples from the Python Client API Reference

```
from minio import Minio
from minio.error import ResponseError

minioClient = Minio('play.minio.io:9000',
                  access_key='Q3AM3UQ867SPQQA43P2F',
                  secret_key='zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG',
                  secure=True)

buckets = minioClient.list_buckets()
for bucket in buckets:
    print(bucket.name, bucket.creation_date)
    notification = minioClient.get_bucket_notification(bucket.name)
    break
```

throws the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/python3.6/site-packages/minio/api.py", line 424, in get_bucket_notification
    return parse_get_bucket_notification(data)
  File "/python3.6/site-packages/minio/parsers.py", line 365, in parse_get_bucket_notification
    root = S3Element.fromstring('GetBucketNotificationResult', data)
  File "/python3.6/site-packages/minio/parsers.py", line 76, in fromstring
    root_name, error.message
minio.error.InvalidXMLError: InvalidXMLError: message: "GetBucketNotificationResult" XML is not parsable. Message: no element found: line 1, column 0
```

**Comment by kannappanr** [comment]
@bdenglish Thanks for filing this issue. I was able to reproduce this issue. 

According to documentation, we are supposed to receive an empty notification structure.

**Comment by bdenglish** [comment]
This is what the javascript library returns:

```
{ TopicConfiguration: [],
  QueueConfiguration: [],
  CloudFunctionConfiguration: [] }
```
The python library fails when there are valid bucket notification subscriptions (the javascript library returns them correctly) so it is a problem even when the result is not empty. However, I don't have an easy way of demonstrating that.

**Comment by krisis** [comment]
@bdenglish with https://github.com/minio/minio-py/pull/697, minio-py would return `{}` for a bucket without notifications.
