### ISSUE TITLE
MemoryError while upload large file

### ISSUE THREAD

**Issue by rbrik** [minio/minio-py#704]
Using **minio-py 4.0.6** to upload large file to a **minio.exe version 2018-10-18T00:28:58Z** failed with a MemoryError:

```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\minio\api.py", line 545, in fput_object
    file_size, content_type, metadata, sse)
  File "C:\Python27\lib\site-packages\minio\api.py", line 773, in put_object
    data, length, metadata=metadata, sse=sse)
  File "C:\Python27\lib\site-packages\minio\api.py", line 1541, in _stream_put_object
    part_data = read_full(data, current_part_size)
  File "C:\Python27\lib\site-packages\minio\helpers.py", line 179, in read_full
    chunk.write(current_data)
MemoryError
```

I run a tests on a Windows 10 machine with 8GB physical memory and a fix configured 8GB virtual memory. The test starts a minio server and upload a 25GB file in the same machine. For each loaded file part the _read_full()_ call increase the used memory until all physical and virtual memory is in use.

**Comment by vadmeste** [comment]
Hey @rbrik, 

Do you have any sample or short code which reproduces the issue ?

**Comment by rbrik** [comment]
Here a short snippet whereby i repeatedly got the exception on a Windows 10 machine with physical memory + virtual memory < file size.

```python
import os
import certifi
import urllib3
import subprocess
import datetime
import filecmp
import shutil
from minio.api import Minio

PORT = '9000'
HOST = 'localhost'
ENDPOINT = '{}:{}'.format(HOST, PORT)
ACCESS_KEY = 'test_access_key'
SECRET_KEY = 'test_secret_key'
MINIO_SERVER_BINARY = r'.\minio.exe'
SERVER_STORAGE_DIRECTORY = r'.\test_minio_storage'
BUCKET_NAME = 'test'
FILE_SIZE = 26843545600 # 25GB
FILE_NAME = 'testFile.txt'
FILE_UPLOAD_DIR = r'.\upload'
FILE_DOWNLOAD_DIR = r'.\download'
FILE_UPLOAD_PATH = os.path.join(FILE_UPLOAD_DIR, FILE_NAME)
FILE_DOWNLOAD_PATH = os.path.join(FILE_DOWNLOAD_DIR, FILE_NAME)

print 'Start a minio-Server @ {}:{}'.format(HOST, PORT)
serverProcess = subprocess.Popen([MINIO_SERVER_BINARY, 'server', SERVER_STORAGE_DIRECTORY])

print 'Start a minio-Client'
httpClient = urllib3.PoolManager(
    timeout=urllib3.Timeout.DEFAULT_TIMEOUT,
    cert_reqs='CERT_REQUIRED',
    ca_certs=certifi.where(),
    retries=urllib3.Retry(
        total=10,
        backoff_factor=0.2,
        status_forcelist=[500, 502, 503, 504]
    )
)
minioClient = Minio(
    ENDPOINT, 
    ACCESS_KEY, 
    SECRET_KEY,
    secure=False,
    region='us-east-1',
    http_client=httpClient
)

print 'Create bucket if necessary'
if not minioClient.bucket_exists(bucket_name=BUCKET_NAME):
    minioClient.make_bucket(BUCKET_NAME)

print 'Create test file'
if not os.path.exists(FILE_UPLOAD_DIR):
    os.makedirs(FILE_UPLOAD_DIR)
with open(FILE_UPLOAD_PATH, 'a') as fileHandle:
    fileHandle.truncate(FILE_SIZE)
    fileHandle.write('changed_@_{}\n'.format(datetime.datetime.now()))

print 'Upload test file'
minioClient.fput_object(BUCKET_NAME, FILE_NAME, FILE_UPLOAD_PATH, metadata={'X-Amz-Meta-Sourcepath':FILE_UPLOAD_PATH})

print 'Download test file'
minioClient.fget_object(BUCKET_NAME, FILE_NAME, FILE_DOWNLOAD_PATH)

print 'Validate download'
result = filecmp.cmp(FILE_UPLOAD_PATH, FILE_DOWNLOAD_PATH, shallow=False)
if result == False:
    raise Exception('The uploaded file {} is different to the downloaded file {}'.format(FILE_UPLOAD_PATH, FILE_DOWNLOAD_PATH))

print 'Kill the minio-Server @ {}:{}...'.format(HOST, PORT)
subprocess.Popen('TASKKILL /F /PID {pid} /T'.format(pid=serverProcess.pid))
```
