### ISSUE TITLE
"ListObjectV2Result" XML is not parsable - probably due to non UTF-8 characters

### ISSUE THREAD

**Issue by trel** [minio/minio-py#716]
When trying to get a full listing of objects in a bucket...

```
minio.error.InvalidXMLError: InvalidXMLError: message: "ListObjectV2Result" XML is not parsable. Message: reference to invalid character number: line 2, column 112949
```
This appears very similar to the explanation given in the s3cmd tool issue comment:
  https://github.com/s3tools/s3cmd/issues/758#issuecomment-406899282

If there are invalid UTF-8 characters in the file names... is there anything minio-py can do to handle this cleanly?

**Comment by kannappanr** [comment]
@trel We will try to reproduce the issue locally. Do you have a sample file name that can be used to reproduce this issue?

**Comment by vadmeste** [comment]
I think AWS is wrong in this, this is an example of a response from AWS:

```
<?xml version="1.0" encoding="UTF-8"?>                               
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>vadmeste-testbucket</Name><Prefix></Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated><Contents><Key>a&#x19;&#x7;</Key><LastModified>2018-12-26T12:03:51.000Z</LastModified><ETag>&quot;d41d8cd98f00b204e9800998ecf8427e&quot;</ETag><Size>0</Size><Owner><ID>f79437bbcf4cb155027ef25a8d29dac63ffbadefa825c406b64cd2ba60453029</ID><DisplayName>devops</DisplayName></Owner><StorageClass>STANDARD</StorageClass></Contents><Contents><Key>a&#x19;a</Key><LastModified>2018-1226T11:59:14.000Z</LastModified><ETag>&quot;d6eb32081c822ed572b70567826d9d9d&quot;</ETag><Size>13</Size><Owner><ID>f79437bbcf4cb155027ef25a8d29dac63ffbadefa825c406b64cd2ba60453029</ID><DisplayName>devops</DisplayName></Owner><StorageClass>STANDARD</StorageClass></Contents></ListBucketResult> 
``` 

According to this document https://www.w3.org/TR/xml/#charsets, `&#x19` is a forbidden character in any XML document, Python XML parser rejects it already but accepts many other characters such as `&#x20`.

```
14:43 $ cat script.py
import xml.etree.ElementTree as ET

xml_text='<?xml version="1.0" encoding="UTF-8"?><root>&#x20;</root>'
root = ET.fromstring(xml_text)

print('&#x20; passed!')

xml_text='<?xml version="1.0" encoding="UTF-8"?><root>&#x19;</root>'
root = ET.fromstring(xml_text)

print('&#x19; passed!')

```

Running the script:

```
14:43 $ python script.py
&#x20; passed!
Traceback (most recent call last):
  File "p.py", line 9, in <module>
    root = ET.fromstring(xml_text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: reference to invalid character number: line 1, column 44

```
