### ISSUE TITLE
Minio rejects valid hostnames

### ISSUE THREAD

**Issue by dwhitlow** [minio/minio-py#760]
The Minio python library rejects hostnames with underscores in them. Since this is a standard separator for docker container names, this causes problems when trying to run Minio as part of a docker compose setup.

For example, with a linked container named `minio_server`, this python session should not raise an error:
```
Python 3.6.8 (default, Mar 27 2019, 08:53:45) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from minio import Minio
>>> Minio('minio_server:9000')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 147, in __init__
    is_valid_endpoint(endpoint)
  File "/usr/local/lib/python3.6/site-packages/minio/helpers.py", line 299, in is_valid_endpoint
    raise InvalidEndpointError('Hostname does not meet URL standards.')
minio.error.InvalidEndpointError: InvalidEndpointError: message: Hostname does not meet URL standards.
```

**Comment by kannappanr** [comment]
@dwhitlow Thanks for filing this issue. We will take a look at it.
