### ISSUE TITLE
minio.error.SignatureDoesNotMatch non ascii metadata

### ISSUE THREAD

**Issue by zukka77** [minio/minio-py#764]
Whenever i try to put an object with non ascii metadata value I get minio.error.SignatureDoesNotMatch

```
Traceback (most recent call last):
  File "testio.py", line 18, in <module>
    minioClient.put_object("test","test.txt",BytesIO(data),len(data),metadata={"test":"testà"})
  File "/tmp/venv/lib/python3.7/site-packages/minio/api.py", line 838, in put_object
    progress=progress)
  File "/tmp/venv/lib/python3.7/site-packages/minio/api.py", line 1551, in _do_put_object
    content_sha256=sha256_hex
  File "/tmp/venv/lib/python3.7/site-packages/minio/api.py", line 1901, in _url_open
    object_name).get_exception()
minio.error.SignatureDoesNotMatch: SignatureDoesNotMatch: message: The request signature we calculated does not match the signature you provided.
```
This works:
```
with open('test.txt','rb') as f:
    data=f.read()
minioClient.put_object("test","test.txt",BytesIO(data),len(data),metadata={"test":"test"})
```
This doesn't:
```
with open('test.txt','rb') as f:
    data=f.read()
minioClient.put_object("test","test.txt",BytesIO(data),len(data),metadata={"test":"testà"})
```

**Comment by kannappanr** [comment]
@zukka77 Thanks for reporting this issue. Will take a look.

**Comment by vadmeste** [comment]
@zukka77 in the following documentation, https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-metadata, it says that 
 `Each key-value pair must conform to US-ASCII when you are using REST`

`é` is not accepted as a header value even in the HTTP spec.

The maximum we can do here is to return an error with a self explanatory error

**Comment by kannappanr** [comment]
ping @vadmeste We can add something like 
```
metadata supports only ASCII characters.
```
