### ISSUE TITLE
Connection isn't established 

### ISSUE THREAD

**Issue by InfiniteLife** [minio/minio-py#779]
I'm running following code:

```
from minio import Minio
from minio.error import ResponseError
import os
from collections import defaultdict

AnnoBucket = "anno"
DataBucket = "data"

minioClient = Minio("storage.mr.*rest of address*",
                  access_key='accesskey',
                  secret_key='secretkey',
                  secure=True)


if not minioClient.bucket_exists(AnnoBucket):
    raise Exception('Not able to find annotations bucket: {}'.format(AnnoBucket))
```
And it works fine on Windows.
But when I am trying to run this code on Ubuntu 18.04, it freezes for forever trying to check the bucket existence:
`minioClient.bucket_exists(AnnoBucket)`

When I interrupt process, here is the output message:
```
Traceback (most recent call last):
  File "collect_data_server.py", line 25, in <module>
    if not minioClient.bucket_exists(AnnoBucket):
  File "/home/zhenin/anaconda3/lib/python3.5/site-packages/minio/api.py", line 362, in bucket_exists
    self._url_open('HEAD', bucket_name=bucket_name)
  File "/home/zhenin/anaconda3/lib/python3.5/site-packages/minio/api.py", line 1856, in _url_open
    region = self._get_bucket_region(bucket_name)
  File "/home/zhenin/anaconda3/lib/python3.5/site-packages/minio/api.py", line 1785, in _get_bucket_region
    region = self._get_bucket_location(bucket_name)
  File "/home/zhenin/anaconda3/lib/python3.5/site-packages/minio/api.py", line 1821, in _get_bucket_location
    headers=headers)
  File "/home/zhenin/anaconda3/lib/python3.5/site-packages/urllib3/poolmanager.py", line 326, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/zhenin/anaconda3/lib/python3.5/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/zhenin/anaconda3/lib/python3.5/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/home/zhenin/anaconda3/lib/python3.5/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/home/zhenin/anaconda3/lib/python3.5/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context)
  File "/home/zhenin/anaconda3/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/zhenin/anaconda3/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/home/zhenin/anaconda3/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/home/zhenin/anaconda3/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/home/zhenin/anaconda3/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()

```

**Comment by nitisht** [comment]
do you have https enabled on the server side @InfiniteLife

**Comment by kannappanr** [comment]
@InfiniteLife Please try this code to connect to Play server and you can find that the code returns right away.

```
from minio import Minio
from minio.error import ResponseError
import os
from collections import defaultdict

AnnoBucket = "anno"
DataBucket = "data"

minioClient = Minio("play.min.io:9000",
                  access_key='Q3AM3UQ867SPQQA43P2F',
                  secret_key='zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG',
                  secure=True)


if not minioClient.bucket_exists(AnnoBucket):
    raise Exception('Not able to find annotations bucket: {}'.format(AnnoBucket))
```

**Comment by InfiniteLife** [comment]
@kannappanr @nitisht yes it works, but for some reason not from the server where is located minio storage. Our admins said that tcp-connect with minio server was established, but replay packet from minio during tls-handshake wasn't received(blocked somewhere). So they had to redirect traffic from minio server through another point and now it works

**Comment by kannappanr** [comment]
@InfiniteLife Closing this issue based on your comment. Please feel free to reach out to us if you have further questions.
