### ISSUE TITLE
unable to access minio using python client

### ISSUE THREAD

**Issue by Nithish-Raja** [minio/minio-py#791]
Minio is running inside a docker container.
Here's the docker command i use to start the container
``` sudo docker run -d --rm --name minio -p 9000:9000 -e MINIO_ACCESS_KEY=admin -e MINIO_SECRET_KEY=adminsecret minio/minio server /data```

Able to access minio through myb browser but python code fails

The python code used to work 2 weeks ago, but it stopped working now

Here is my python code,
```from minio import Minio

minioClient = Minio('0.0.0.0:9000', access_key="admin", secret_key="adminsecret", secure=False)

print("\n# Checking if 'mybucket' exists\n")
if not minioClient.bucket_exists("mybucket"):
    print("# bucket does not exist, creating new bucket\n")
    minioClient.make_bucket("mybucket", location="us-east-1")
else:
    print("# bucket exists\n")

minioClient.fput_object('mybucket', 'myobject.csv', 'myobject.csv')

objects = minioClient.list_objects('mybucket', prefix='my-prefixname',
                              recursive=True)
for obj in objects:
    print(obj.bucket_name, obj.object_name.encode('utf-8'), obj.last_modified,
          obj.etag, obj.size, obj.content_type)
```
Here is the stack trace i get

```
# Checking if 'mybucket' exists
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f1b84be3290>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "index.py", line 9, in <module>
    if not minioClient.bucket_exists("mybucket"):
  File "/usr/local/lib/python3.7/site-packages/minio/api.py", line 402, in bucket_exists
    self._url_open('HEAD', bucket_name=bucket_name)
  File "/usr/local/lib/python3.7/site-packages/minio/api.py", line 1907, in _url_open
    region = self._get_bucket_region(bucket_name)
  File "/usr/local/lib/python3.7/site-packages/minio/api.py", line 1836, in _get_bucket_region
    region = self._get_bucket_location(bucket_name)
  File "/usr/local/lib/python3.7/site-packages/minio/api.py", line 1872, in _get_bucket_location
    headers=headers)
  File "/usr/local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 326, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=9000): Max retries exceeded with url: /mybucket?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1b84be3290>: Failed to establish a new connection: [Errno 111] Connection refused'))```

**Comment by Nithish-Raja** [comment]
I inspected the docker bridge and found that i was sending my request to the wrong gateway. Once i fixed it, the problem was resolved.

**Comment by siteshi** [comment]
I am having the same problem, could you please post your solution in detail?

**Comment by Nithish-Raja** [comment]
Initially i assumed that the minio server was running on `0.0.0.0:9000` and i tried to access it there. However, upon inspecting the network bridge, it wasn't running on `0.0.0.0`. Making that change in my client code enabled the connection to be successful. Run ```sudo docker network inspect bridge``` to check the network.

**Comment by YehuditShtainberg** [comment]
i try with 0.0.0.0 and with 127.0.0.1 and both failed
