### ISSUE TITLE
minio.error.SignatureDoesNotMatch: 

### ISSUE THREAD

**Issue by petersedivec** [minio/minio-py#795]
## Expected Behavior
Expect the put_object method in minio/api.py to successfully load files into minio.

## Current Behavior
We are running a script that iterates through every file (subfolders included) and pushes all of those files up to a minio bucket with the api.  We are using SSE with an SSE master key, not vault.  We have a total of 4 buckets and hence plan to run the script 4 times from each folder on local HDD.  We manged to get through 67GB upload before it failed

$ python /group/transfer/minio_push.py
Traceback (most recent call last):
  File "/group/transfer/minio_push.py", line 60, in <module>
    minioClient.put_object(bucket_name, pathfile, file_data, file_stat.st_size)
  File "/usr/lib/python2.7/site-packages/minio/api.py", line 878, in put_object
    progress=progress)
  File "/usr/lib/python2.7/site-packages/minio/api.py", line 1602, in _do_put_object
    content_sha256=sha256_hex
  File "/usr/lib/python2.7/site-packages/minio/api.py", line 1952, in _url_open
    object_name).get_exception()
minio.error.SignatureDoesNotMatch: SignatureDoesNotMatch: message: The request signature we calculated does not match the signature you provided.

## Steps to Reproduce (for bugs)
Not sure how to reproduce at the moment, we are attempting to reproduce on the objects it failed.  We're not sure how/why it loaded 67GB of files out of 275GB for one bucket and then threw this error.  

## Context
We are attempting to load ~2.5TB of data into minio for our project

## Your Environment

* Version used (`minio version`): latest version of minio-py
* Environment name and version (e.g. nginx 1.9.1): minio is running as a docker container with following release: minio:RELEASE.2019-06-01T03-46-14Z (we plan to update this
* Server type and version: RHEL 7.6 w/ Docker EE
* Link to your project: our project is not public

**Comment by harshavardhana** [comment]
Does your object name have any special characters in it ?

**Comment by petersedivec** [comment]
We do have files with special chars in it, but it looks like it failed on potentially files with white space in their names, not sure if those are considered special characters.  filenames like "Bio M Fiori.doc".  Given that we managed to upload 67GB of data i'm a little surprised if this was the first special char name we found

**Comment by kannappanr** [comment]
@petersedivec I tried to upload a file with spaces in it and it seemed to go through just fine. I tried it against `play` and another distributed setup

```
from minio import Minio
from minio.error import ResponseError

client = Minio('play.min.io',
               access_key='Q3AM3UQ867SPQQA43P2F',
               secret_key='zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG')

try:
    client.fput_object('mybucket', 'my file with a space.txt', '/home/admin/my file with a space.txt')
except ResponseError as err:
    print(err)
```

So, I don't think it is related to that. Do you have a sample code and can you also let us know the version of `minio-py` you are using?

**Comment by petersedivec** [comment]
We are doing some more investigation and have updated our script to catch
the specific SignatureDoesNotMatch error as well as any other errors Minio
might throw.  We have also tested with files with spaces and special
characters and not been able to reproduce the error.  Our updated script
completed running against one of our 4 buckets, one that previously failed
and it successfully loaded all of the objects except for one which was

//bucket/990500~1 (1).XLS/990500~1 (1).XLS

We are running the remaining 3 buckets and will figure out how many total
files error out and if there's a pattern.

I'll get back to you on the minio-py version.  My assumption is the latest
but to be sure we need to check what version is running in our client's
data center, i don't want to assume it's the same we're running locally.

**Comment by petersedivec** [comment]
yep, thanks for sharing, i see that.  we'll follow this thread and
hopefully retest this week.  Seems like this issue might be closed in next
day or two.

**Comment by blmayer** [comment]
I think this hasn't been fixed, I just ran into the same issue. I'm using version 5.0.10.

**Comment by balamurugana** [comment]
@blmayer can you enable `minio_client.trace_on(sys.stdout)` and share the output?

**Comment by blmayer** [comment]
Sure!

The command:

```minio_client.put_object(
    '<mybucketname>',
    "some~name.txt",
    BytesIO(b'blahblahblah\n'),
    len('blahblahblah\n')
)```

```---------START-HTTP---------
PUT /<mybucketname>/some~name.txt HTTP/1.1
User-Agent: MinIO (Darwin; x86_64) minio-py/5.0.10
Content-Length: 13
Content-Md5: jDwaYLXBDz+qzRWuOx22+w==
Content-Type: application/octet-stream
Host: s3.fr-par.scw.cloud
X-Amz-Date: 20200520T144308Z
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/minio/helpers.py:124: FutureWarning: Possible nested set at position 12
  v = re.sub(r'Signature=([[0-9a-f]+)', 'Signature=*REDACTED*', v)
Authorization: AWS4-HMAC-SHA256 Credential=SCW9VJPZST931SCF3WHR/20200520/fr-par/s3/aws4_request, SignedHeaders=content-length;content-md5;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 403
X-Amz-Id-2: tx4fbe203f77394bbf98f1d-005ec541fd
X-Amz-Request-Id: tx4fbe203f77394bbf98f1d-005ec541fd
Content-Type: application/xml
Date: Wed, 20 May 2020 14:43:09 GMT
Transfer-Encoding: chunked
b''---------END-HTTP---------
Traceback (most recent call last):
  File "/<pathtothecode>/src/githubtest.py", line 21, in <module>
    len('blahblahblah\n')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/minio/api.py", line 972, in put_object
    progress=progress)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/minio/api.py", line 1689, in _do_put_object
    content_sha256=sha256_hex
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/minio/api.py", line 2020, in _url_open
    object_name).get_exception()
minio.error.SignatureDoesNotMatch: SignatureDoesNotMatch: message: The request signature we calculated does not match the signature you provided.
```

I only hid the the bucket name and the path after pasting.

**Comment by balamurugana** [comment]
@blmayer I see `PUT /<mybucketname>/some~name.txt HTTP/1.1` might cause a problem. I will try to reproduce and will get back to you.

**Comment by blmayer** [comment]
Thanks!

**Comment by balamurugana** [comment]
@blmayer I tried below python code works fine with `s3.amazonaws.com` and `play.minio.io:9000`
```python
import io
import sys
from minio import Minio

client = Minio(
    sys.argv[1], access_key=sys.argv[2], secret_key=sys.argv[3],
)
client.put_object(
    "bala-test-bucket1", "some~name.txt", io.BytesIO(b"hello"), 5,
)
```

It looks like some other issue you got like your proxy with wrong configuration or server issue.

**Comment by blmayer** [comment]
Interesting. I think it can be server side, but I also tried using the `boto3` library, and it worked. Here's the code:

```
scw = boto3.Session(region_name="fr-par")
storage = scw.resource(
    's3',
    endpoint_url=_url,
    aws_access_key_id=_key_id,
    aws_secret_access_key=_key
)
files = storage.Bucket('<mybucket>')

files.put_object(
    Key="some~file.txt",
    Body=bytes('blahblahblah\n', 'utf-8')
)
```

I have a hunch that it may be related to the http client used under the hood, but no clue on how to test it.

**Comment by balamurugana** [comment]
My guess is that the server is expecting signature v2 whereas `minio-py` supports signature v4. Could you check on that?

**Comment by blmayer** [comment]
I'll try that and come back to you.

**Comment by balamurugana** [comment]
@blmayer Could you enable debugging in `boto3` something like `boto3.set_stream_logger(name='botocore')` and share the output?

**Comment by blmayer** [comment]
Thanks for the suggestion, here it goes:

```
2020-05-23 15:49:59,900 botocore.hooks [DEBUG] Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2020-05-23 15:49:59,904 botocore.hooks [DEBUG] Changing event name from before-call.apigateway to before-call.api-gateway
2020-05-23 15:49:59,904 botocore.hooks [DEBUG] Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2020-05-23 15:49:59,906 botocore.hooks [DEBUG] Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2020-05-23 15:49:59,907 botocore.hooks [DEBUG] Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2020-05-23 15:49:59,907 botocore.hooks [DEBUG] Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2020-05-23 15:49:59,908 botocore.hooks [DEBUG] Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2020-05-23 15:49:59,911 botocore.hooks [DEBUG] Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2020-05-23 15:49:59,911 botocore.hooks [DEBUG] Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2020-05-23 15:49:59,911 botocore.hooks [DEBUG] Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2020-05-23 15:49:59,911 botocore.hooks [DEBUG] Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2020-05-23 15:49:59,912 botocore.session [DEBUG] Setting config variable for region to 'fr-par'
2020-05-23 15:49:59,928 botocore.loaders [DEBUG] Loading JSON file: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/boto3/data/s3/2006-03-01/resources-1.json
2020-05-23 15:49:59,929 botocore.loaders [DEBUG] Loading JSON file: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/data/endpoints.json
2020-05-23 15:49:59,933 botocore.hooks [DEBUG] Event choose-service-name: calling handler <function handle_service_name_alias at 0x10dd3fd08>
2020-05-23 15:49:59,952 botocore.loaders [DEBUG] Loading JSON file: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/data/s3/2006-03-01/service-2.json
2020-05-23 15:49:59,966 botocore.hooks [DEBUG] Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x10ddbaa60>
2020-05-23 15:49:59,966 botocore.hooks [DEBUG] Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x10deea8c8>
2020-05-23 15:49:59,979 botocore.hooks [DEBUG] Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x10ddba840>
2020-05-23 15:49:59,979 botocore.client [DEBUG] Assuming an endpoint for s3, fr-par: https://s3.fr-par.scw.cloud
2020-05-23 15:49:59,979 botocore.args [DEBUG] The s3 config key is not a dictionary type, ignoring its value of: None
2020-05-23 15:49:59,990 botocore.endpoint [DEBUG] Setting s3 timeout as (60, 60)
2020-05-23 15:49:59,993 botocore.loaders [DEBUG] Loading JSON file: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/botocore/data/_retry.json
2020-05-23 15:49:59,996 botocore.client [DEBUG] Registering retry handlers for service: s3
2020-05-23 15:49:59,999 botocore.client [DEBUG] Using S3 path style addressing.
2020-05-23 15:50:00,003 botocore.hooks [DEBUG] Event creating-resource-class.s3.Bucket: calling handler <function lazy_call.<locals>._handler at 0x10df58510>
2020-05-23 15:50:00,005 botocore.hooks [DEBUG] Event creating-resource-class.s3.Bucket: calling handler <function lazy_call.<locals>._handler at 0x10df58510>
2020-05-23 15:50:00,017 botocore.hooks [DEBUG] Event before-parameter-build.s3.PutObject: calling handler <function validate_ascii_metadata at 0x10de1a1e0>
2020-05-23 15:50:00,017 botocore.hooks [DEBUG] Event before-parameter-build.s3.PutObject: calling handler <function sse_md5 at 0x10de19620>
2020-05-23 15:50:00,017 botocore.hooks [DEBUG] Event before-parameter-build.s3.PutObject: calling handler <function convert_body_to_file_like_object at 0x10de1a9d8>
2020-05-23 15:50:00,017 botocore.hooks [DEBUG] Event before-parameter-build.s3.PutObject: calling handler <function validate_bucket_name at 0x10de19598>
2020-05-23 15:50:00,017 botocore.hooks [DEBUG] Event before-parameter-build.s3.PutObject: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x10e427390>>
2020-05-23 15:50:00,018 botocore.hooks [DEBUG] Event before-parameter-build.s3.PutObject: calling handler <function generate_idempotent_uuid at 0x10de191e0>
2020-05-23 15:50:00,018 botocore.hooks [DEBUG] Event before-call.s3.PutObject: calling handler <function conditionally_calculate_md5 at 0x10de19510>
2020-05-23 15:50:00,018 botocore.hooks [DEBUG] Event before-call.s3.PutObject: calling handler <function add_expect_header at 0x10de198c8>
2020-05-23 15:50:00,018 botocore.handlers [DEBUG] Adding expect 100 continue header to request.
2020-05-23 15:50:00,019 botocore.hooks [DEBUG] Event before-call.s3.PutObject: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x10e427390>>
2020-05-23 15:50:00,019 botocore.hooks [DEBUG] Event before-call.s3.PutObject: calling handler <function inject_api_version_header_if_needed at 0x10de1aae8>
2020-05-23 15:50:00,019 botocore.endpoint [DEBUG] Making request for OperationModel(name=PutObject) with params: {'url_path': '/<bucket>/<some>/<path>/some~file.txt', 'query_string': {}, 'method': 'PUT', 'headers': {'User-Agent': 'Boto3/1.9.163 Python/3.7.3 Darwin/19.3.0 Botocore/1.12.163 Resource', 'Content-MD5': '1B2M2Y8AsgTpgAmY7PhCfg==', 'Expect': '100-continue'}, 'body': <_io.BytesIO object at 0x10e421f10>, 'url': 'https://s3.fr-par.scw.cloud/<bucket>/<some>/<path>/some~file.txt', 'context': {'client_region': 'fr-par', 'client_config': <botocore.config.Config object at 0x10e319be0>, 'has_streaming_input': True, 'auth_type': None, 'signing': {'bucket': '<bucket>'}}}
2020-05-23 15:50:00,019 botocore.hooks [DEBUG] Event request-created.s3.PutObject: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x10e319780>>
2020-05-23 15:50:00,019 botocore.hooks [DEBUG] Event choose-signer.s3.PutObject: calling handler <function set_operation_specific_signer at 0x10de190d0>
2020-05-23 15:50:00,020 botocore.auth [DEBUG] Calculating signature using v4 auth.
2020-05-23 15:50:00,020 botocore.auth [DEBUG] CanonicalRequest:
PUT
/<bucket>/<some>/<path>/some~file.txt

content-md5:1B2M2Y8AsgTpgAmY7PhCfg==
host:s3.fr-par.scw.cloud
x-amz-content-sha256:UNSIGNED-PAYLOAD
x-amz-date:20200523T185000Z

content-md5;host;x-amz-content-sha256;x-amz-date
UNSIGNED-PAYLOAD
2020-05-23 15:50:00,020 botocore.auth [DEBUG] StringToSign:
AWS4-HMAC-SHA256
20200523T185000Z
20200523/fr-par/s3/aws4_request
f73676a09ea294554141e7b917a63e526d22a43458e36c14009ea1215f7bfba5
2020-05-23 15:50:00,020 botocore.auth [DEBUG] Signature:
6956075cdb2760fd577c5639f73e4297af9754f56d95e0bf83989ca261230842
2020-05-23 15:50:00,021 botocore.endpoint [DEBUG] Sending http request: <AWSPreparedRequest stream_output=False, method=PUT, url=https://s3.fr-par.scw.cloud/<bucket>/<some>/<path>/some~file.txt, headers={'User-Agent': b'Boto3/1.9.163 Python/3.7.3 Darwin/19.3.0 Botocore/1.12.163 Resource', 'Content-MD5': b'1B2M2Y8AsgTpgAmY7PhCfg==', 'Expect': b'100-continue', 'X-Amz-Date': b'20200523T185000Z', 'X-Amz-Content-SHA256': b'UNSIGNED-PAYLOAD', 'Authorization': b'AWS4-HMAC-SHA256 Credential=SCW9VJPZST931SCF3WHR/20200523/fr-par/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=6956075cdb2760fd577c5639f73e4297af9754f56d95e0bf83989ca261230842', 'Content-Length': '0'}>
2020-05-23 15:50:00,941 botocore.awsrequest [DEBUG] Waiting for 100 Continue response.
2020-05-23 15:50:01,248 botocore.awsrequest [DEBUG] 100 Continue response seen, now sending request body.
2020-05-23 15:50:01,276 botocore.parsers [DEBUG] Response headers: {'Content-Length': '0', 'x-amz-id-2': 'txd406bf7f35ab4636b46fb-005ec97059', 'Last-Modified': 'Sat, 23 May 2020 18:50:01 GMT', 'ETag': '"d41d8cd98f00b204e9800998ecf8427e"', 'x-amz-request-id': 'txd406bf7f35ab4636b46fb-005ec97059', 'x-amz-version-id': '1590259801160379', 'Content-Type': 'text/html; charset=UTF-8', 'Date': 'Sat, 23 May 2020 18:50:01 GMT'}
2020-05-23 15:50:01,277 botocore.parsers [DEBUG] Response body:
b''
2020-05-23 15:50:01,278 botocore.hooks [DEBUG] Event needs-retry.s3.PutObject: calling handler <botocore.retryhandler.RetryHandler object at 0x10e4272e8>
2020-05-23 15:50:01,278 botocore.retryhandler [DEBUG] No retry needed.
2020-05-23 15:50:01,278 botocore.hooks [DEBUG] Event needs-retry.s3.PutObject: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x10e427390>>
2020-05-23 15:50:01,280 botocore.hooks [DEBUG] Event creating-resource-class.s3.Object: calling handler <function lazy_call.<locals>._handler at 0x10df58598>
```

**Comment by balamurugana** [comment]
Thanks for the info. It seems I need to get an account in scaleway to debug the issue.
Could you please check whether you are able to create same file in `play.min.io`? I just want to make sure that you don't have any setup issue.

```
			"url": "https://play.minio.io:9000",
			"accessKey": "Q3AM3UQ867SPQQA43P2F",
			"secretKey": "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG",
```

**Comment by blmayer** [comment]
It worked.

```
---------START-HTTP---------
PUT /files/some~name.txt HTTP/1.1
User-Agent: MinIO (Darwin; x86_64) minio-py/5.0.10
Content-Length: 13
Content-Md5: jDwaYLXBDz+qzRWuOx22+w==
Content-Type: application/octet-stream
Host: play.minio.io:9000
X-Amz-Date: 20200524T133851Z
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/minio/helpers.py:124: FutureWarning: Possible nested set at position 12
  v = re.sub(r'Signature=([[0-9a-f]+)', 'Signature=*REDACTED*', v)
Authorization: AWS4-HMAC-SHA256 Credential=Q3AM3UQ867SPQQA43P2F/20200524/us-east-1/s3/aws4_request, SignedHeaders=content-length;content-md5;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 200
Accept-Ranges: bytes
Content-Length: 0
Content-Security-Policy: block-all-mixed-content
Etag: "97cb34eec30bc11a70ec264201f5b9ca-1"
Server: MinIO/DEVELOPMENT.2020-05-19T09-33-19Z
Vary: Origin
X-Amz-Request-Id: 1611FA76E915962A
X-Xss-Protection: 1; mode=block
Date: Sun, 24 May 2020 13:38:52 GMT
---------END-HTTP---------
```

**Comment by blmayer** [comment]
This is their documentation: [link](https://www.scaleway.com/en/docs/object-storage-feature/).

It is said they only support AWS signature v4. I hope it may be helpful.

**Comment by balamurugana** [comment]
@blmayer I see it is working.
```python

>>> c = Minio("s3.fr-par.scw.cloud", "<ACCESS_KEY>", "<SECRET_KEY>", region="fr-par")
>>> c.trace_on(sys.stdout)
>>> c.put_object("bala-test-bucket", "some~name.txt", io.BytesIO(b"hello"), 5)
---------START-HTTP---------
PUT /bala-test-bucket/some~name.txt HTTP/1.1
User-Agent: MinIO (Linux; x86_64) minio-py/5.0.10
Content-Length: 5
Content-Md5: XUFAKrxLKna5cZ2REBfFkg==
Content-Type: application/octet-stream
Host: s3.fr-par.scw.cloud
X-Amz-Date: 20200526T055432Z
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
Authorization: AWS4-HMAC-SHA256 Credential=<ACCESS_KEY>/20200526/fr-par/s3/aws4_request, SignedHeaders=content-length;content-md5;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 200
Content-Length: 0
X-Amz-Id-2: tx640d9396cf0d49ea922ed-005eccaf1c
Last-Modified: Tue, 26 May 2020 05:54:36 GMT
Etag: "5d41402abc4b2a76b9719d911017c592"
X-Amz-Request-Id: tx640d9396cf0d49ea922ed-005eccaf1c
X-Amz-Version-Id: 1590472476260864
Content-Type: text/html; charset=UTF-8
Date: Tue, 26 May 2020 05:54:36 GMT
---------END-HTTP---------
'5d41402abc4b2a76b9719d911017c592'
>>> list(c.get_object("bala-test-bucket", "some~name.txt"))
---------START-HTTP---------
GET /bala-test-bucket/some~name.txt HTTP/1.1
User-Agent: MinIO (Linux; x86_64) minio-py/5.0.10
Host: s3.fr-par.scw.cloud
X-Amz-Date: 20200526T055817Z
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
Authorization: AWS4-HMAC-SHA256 Credential=<ACCESS_KEY>/20200526/fr-par/s3/aws4_request, SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*

HTTP/1.1 200
Content-Length: 5
X-Amz-Id-2: tx03da956fb0cb4e2a94209-005eccaffd
Accept-Ranges: bytes
Last-Modified: Tue, 26 May 2020 05:54:36 GMT
Etag: "5d41402abc4b2a76b9719d911017c592"
X-Amz-Request-Id: tx03da956fb0cb4e2a94209-005eccaffd
X-Amz-Version-Id: 1590472476260864
Content-Type: application/octet-stream
Date: Tue, 26 May 2020 05:58:21 GMT
---------END-HTTP---------
[b'hello']
>>> 
```

I think there is some other problem at your side.
