### ISSUE TITLE
stat_object access denied

### ISSUE THREAD

**Issue by yashas123** [minio/minio-py#828]
When I try to use 'folder_1/001.jpg' for object name, stat_object gives this traceback.
When the image actually does exist in folder_1 when I check in minio file browser and is perfectly accessible when I share it . Please help.

```
Traceback (most recent call last):
  File "store.py", line 29, in <module>
    'folder_1/001.jpg',

  File "C:\ProgramData\Anaconda3\lib\site-packages\minio\api.py", line 978, in stat_object
    object_name=object_name, headers=headers)
  File "C:\ProgramData\Anaconda3\lib\site-packages\minio\api.py", line 1881, in _url_open
    object_name).get_exception()
minio.error.NoSuchKey: NoSuchKey: message: The specified key does not exist.
```

**Comment by yashas123** [comment]
Ok, since I had migrated image from a different server using rsync, I had to change ownership, now i'm getting the error as:
Traceback (most recent call last):
  File "store.py", line 29, in <module>
    'folder_1/001.jpg',
  File "C:\ProgramData\Anaconda3\lib\site-packages\minio\api.py", line 978, in stat_object
    object_name=object_name, headers=headers)
  File "C:\ProgramData\Anaconda3\lib\site-packages\minio\api.py", line 1881, in _url_open
    object_name).get_exception()
minio.error.AccessDenied: AccessDenied: message: Access Denied

**Comment by yashas123** [comment]
I have checked almost all features, only stat_object is not working.

**Comment by kannappanr** [comment]
@yashas123 It has to be some sort of permission for the user running minio. This has got nothing to do with minio-py

Here is a sample 

```
from minio import Minio
from minio.error import ResponseError

client = Minio('play.min.io',
               access_key='minio',
               secret_key='minio123')

# Fetch stats on your object.
try:
    print(client.stat_object('lll', 'folder_1/001.jpg'))
except ResponseError as err:
    print(err)
```
This works against `play`

**Comment by harshavardhana** [comment]
Please share the code @yashas123

**Comment by yashas123** [comment]
@harshavardhana I'm using it with django as storage class:
```
@deconstructible
class MinioStorage(Storage):

    def __init__(self):
        self.s3 = Minio(settings.M_ENDPOINT_URL,\
              access_key=settings.M_ACCESS_KEY,\
              secret_key=settings.M_SECRET_KEY,\
              secure=True\
        )
        return super(MinioStorage, self).__init__()

    # ...
    def exists(self, name):
        try:
            if self.s3.stat_object(settings.M_BUCKET_NAME, name):
                return True
        except:
            pass
        return False

**Comment by kannappanr** [comment]
@yashas123 Can you please run `mc admin trace -v -a ` against your minio server and try this command again and return us the output. Also, if you are seeing any logs on the console, can you paste them also ?

Also, instead of `rsync`, if you add an object using say `minio-py`, are you seeing this issue?

**Comment by yashas123** [comment]
@kannappanr I used rsync for only restoring some of the images from a different server, I have been still using minio and have been adding new images, and all of the newly added images are uploaded using minio-py sdk, and yet its the same.

And about admin trace, this is what I get:
`mc: <ERROR> Cannot listen to http trace. Server expects client requests with 'admin' API version 'v2', found 'v1', please upgrade the client to latest releases.`

**Comment by harshavardhana** [comment]
As the message suggests you must upgrade the client `mc` @yashas123

**Comment by kannappanr** [comment]
@yashas123 Closing this issue as stale. Will re-open the issue once we have the info requested to look at.

**Comment by yashas123** [comment]
@kannappanr Sorry about that, I thought about testing it out but since the server was already on production use I thought i'll do it later and forgot about it. BTW here `website` is **also** the bucket name
```
aaatest.website.com [REQUEST s3.GetBucketLocation] 20:38:22.566
aaatest.website.com GET /website?location=
aaatest.website.com Host: aaatest.website.com
aaatest.website.com Accept-Encoding: gzip
aaatest.website.com Authorization: AWS4-HMAC-SHA256 Credential=[REDACTED]/                                                                                                                                                        20200409/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=[REDACTED]
aaatest.website.com Cdn-Loop: cloudflare
aaatest.website.com Content-Length: 0
aaatest.website.com X-Real-Ip: [REDACTED]
aaatest.website.com X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
aaatest.website.com X-Forwarded-For: [REDACTED]
aaatest.website.com X-Forwarded-Proto: https
aaatest.website.com Cf-Ipcountry: IN
aaatest.website.com Cf-Ray: 581708037ba1f8d7-NRT
aaatest.website.com X-Amz-Date: 20200409T203821Z
aaatest.website.com Cf-Connecting-Ip: [REDACTED]
aaatest.website.com Cf-Visitor: {"scheme":"https"}
aaatest.website.com
aaatest.website.com [RESPONSE] [20:38:22.566] [ Duration 406µs  ↑ 183 B  ↓ 378 B ]
aaatest.website.com 200 OK
aaatest.website.com Content-Length: 128
aaatest.website.com Content-Security-Policy: block-all-mixed-content
aaatest.website.com Content-Type: application/xml
aaatest.website.com Server: MinIO/RELEASE.2020-04-04T05-39-31Z
aaatest.website.com Vary: Origin
aaatest.website.com X-Amz-Request-Id: 1604413DD522DE42
aaatest.website.com X-Xss-Protection: 1; mode=block
aaatest.website.com Accept-Ranges: bytes
aaatest.website.com <?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/"></LocationConstraint>
aaatest.website.com
aaatest.website.com [REQUEST s3.GetObject] 20:38:23.313
aaatest.website.com GET /website/folder_1/001.jpg
aaatest.website.com Host: aaatest.website.com
aaatest.website.com Cf-Connecting-Ip: [REDACTED]
aaatest.website.com Cf-Ray: 581708084c70f8d7-NRT
aaatest.website.com X-Forwarded-Proto: https
aaatest.website.com User-Agent: Minio (Windows; AMD64) minio-py/4.0.12
aaatest.website.com X-Real-Ip: [REDACTED]
aaatest.website.com Accept-Encoding: gzip
aaatest.website.com Content-Length: 0
aaatest.website.com X-Forwarded-For: [REDACTED]
aaatest.website.com Cf-Visitor: {"scheme":"https"}
aaatest.website.com X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
aaatest.website.com X-Amz-Date: 20200409T203822Z
aaatest.website.com Authorization: AWS4-HMAC-SHA256 Credential=[REDACTED]/                                                                                                                                                        20200409/us-east-1/s3/aws4_request, SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date, Signature=[REDACTED]
aaatest.website.com Cdn-Loop: cloudflare
aaatest.website.com Cf-Ipcountry: IN
aaatest.website.com <BODY>
aaatest.website.com [RESPONSE] [20:38:23.313] [ Duration 375µs  ↑ 194 B  ↓ 780 B ]
aaatest.website.com 403 Forbidden
aaatest.website.com Content-Length: 523
aaatest.website.com Content-Security-Policy: block-all-mixed-content
aaatest.website.com Content-Type: application/xml
aaatest.website.com Server: MinIO/RELEASE.2020-04-04T05-39-31Z
aaatest.website.com Vary: Origin
aaatest.website.com X-Amz-Request-Id: 1604413E019EAAAF
aaatest.website.com X-Xss-Protection: 1; mode=block
aaatest.website.com Accept-Ranges: bytes
aaatest.website.com <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>folder_1/001.jpg</Key><BucketName>website</BucketName><Resource>/website/folder_1/001.jpg</Resource><RequestId>1604413E019EAAAF</RequestId><HostId>6fad8e93-70a0-4293-9164-bc7452ee172f</HostId></Error>

```

**Comment by yashas123** [comment]
Thought it shows SignatureDoesNotMatch in there, in my cmd as usual I got a `minio.error.AccessDenied: AccessDenied: message: Access Denied`
