### ISSUE TITLE
TypeError in copy_object()

### ISSUE THREAD

**Issue by pozsa** [minio/minio-py#851]
The following code results in TypeError within copy_object().
Am I doing something wrong or this is a bug?

```python
def update_document(
        uuid: str,
        response: responses.Response,
        metadata_in: schema.DocumentUpdate,
) -> models.document.Document:
    if not minio_client.bucket_exists(BUCKET):
        raise exception.NotFoundException('document', uuid)

    try:
        stat_object = minio_client.stat_object(BUCKET, uuid)
    except minio.error.NoSuchKey:
        raise exception.NotFoundException('document', uuid)

    object_source = f'/{BUCKET}/{uuid}'
    copy_conditions = minio.CopyConditions()
    copy_conditions.set_match_etag(stat_object.etag)

    minio_client.copy_object(bucket_name=BUCKET,
                             object_name=uuid,
                             object_source=object_source,
                             conditions=copy_conditions,
                             metadata=metadata_in.dict())

    # refresh
    stat_object = minio_client.stat_object(BUCKET, uuid)
    href = minio_client.presigned_get_object(BUCKET, uuid,
                                             datetime.timedelta(minutes=30))
    minio_document = models.document.Document.from_stat_object(stat_object)
    minio_document.href = href

    response.headers['ETag'] = stat_object.etag
    return minio_document
```

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 140, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 134, in __call__
    await self.error_middleware(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 178, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 156, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 140, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 590, in __call__
    await route(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 208, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 129, in app
    raw_response = await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 25, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./app/endpoints/document.py", line 123, in update_document
    minio_client.copy_object(bucket_name=BUCKET,
  File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 812, in copy_object
    response = self._url_open('PUT',
  File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 1935, in _url_open
    response = self._http.urlopen(method, url,
  File "/usr/local/lib/python3.8/site-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1271, in _send_request
    self.putheader(hdr, value)
  File "/usr/local/lib/python3.8/http/client.py", line 1207, in putheader
    if _is_illegal_header_value(values[i]):
TypeError: expected string or bytes-like object
```

**Comment by pozsa** [comment]
I've figured it out. One of the elements in my metadata dict is a `datetime.date`.
Had to convert it to string before passing it to copy_object().

added code:
```python
metadata = metadata_in.dict()
metadata['date'] = str(metadata_in.date)
```

And then passing metadata to metadata in copy_object().
