### ISSUE TITLE
AWS IAM Credential using subscripts on not subscriptable objects

### ISSUE THREAD

**Issue by febg** [minio/minio-py#857]
When trying to use the IamEc2MetaData provider like this:
```
from minio import Minio
from minio.credentials import IamEc2MetaData, Credentials

# Initialize Minio with IamEc2MetaData default credentials object
client = Minio('s3.amazonaws.com',
               credentials=Credentials(provider=IamEc2MetaData()))


buckets = client.list_buckets()
```
I got the following error:
```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    client.list_buckets()
  File "/usr/local/lib/python2.7/site-packages/minio/api.py", line 411, in list_buckets
    raise AccessDenied(response)
minio.error.AccessDenied: AccessDenied: message: Access Denied
```

After doing some digging on why my credentials were not working I found the root cause:

IamEc2MetaData provider is trying to access http response data and status using subscripts throwing the following error:
```
TypeError: 'HTTPResponse' object is not subscriptable
```

**Comment by balamurugana** [comment]
Fixed by https://github.com/minio/minio-py/pull/858
