### ISSUE TITLE
fget_object is inconsistent with key error in kubeflow pipeline deployment.

### ISSUE THREAD

**Issue by srivignessh** [minio/minio-py#932]
I get this key error during the kubeflow pipeline deployment frequently (3 / 10).

Traceback (most recent call last):
  File "run.py", line 74, in <module>
    minio_client.fget_object(raw_data_path, constants.RAW_DATA_PATH)
  File "/app/shared/minio_client.py", line 33, in fget_object
    minioClient.fget_object(bucket_name, object_name, file_path)
  File "/usr/local/lib/python3.6/dist-packages/minio/api.py", line 719, in fget_object
    stat = self.stat_object(bucket_name, object_name, sse)
  File "/usr/local/lib/python3.6/dist-packages/minio/api.py", line 1139, in stat_object
    object_name=object_name, headers=headers)
  File "/usr/local/lib/python3.6/dist-packages/minio/api.py", line 2020, in _url_open
    object_name).get_exception()
minio.error.NoSuchKey: NoSuchKey: message: The specified key does not exist.

Environment: Kubeflow pipelines with the default settings
# kubectl get pods | grep minio
minio-0                                                                  1/1     Running            0          4d20h
minio-1                                                                   1/1     Running            0          4d20h
minio-2                                                                  1/1     Running            0          4d20h
minio-3                                                                  1/1     Running            0          4d20h
minio-5dc88dd55c-bft7l                                     1/1     Running            0          94d

Operations: 1> file put is made from client1 in stage1 
                     2> file get is made from client2 in stage2. 

The error is noticed in the file get operation in stage2.

Not sure the exact cause 

Is there any approach to avoid this error? 
 -> Welcome to suggestions 
 -> Open to increasing default timeouts

**Comment by srivignessh** [comment]
Simple retry on gets didn't solve the issue but the following helped. 

http_client retry object reset every time after the key error.

minioClient._http.connection_pool_kw['retries'] = urllib3.Retry(total=5, backoff_factor=0.2, status_forcelist=[500, 502, 503, 504])

Is there a clean way to do this?

**Comment by srivignessh** [comment]
Creating a Minio client with http_client field set works. The default None does create the http_client properly but doesn't work properly after key error. 

import urllib3

_http = urllib3.PoolManager(
                        timeout=urllib3.Timeout.DEFAULT_TIMEOUT,
                        retries=urllib3.Retry(
                            total=5,
                            backoff_factor=0.2,
                            status_forcelist=[500, 502, 503, 504]
                        )) 

minioClient = Minio('your_hostname.sampledomain.com:9000',
access_key='ACCESS_KEY',
secret_key='SECRET_KEY',
secure=True,
http_client=_http)

Thanks
