### ISSUE TITLE
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='***', port=443): Max retries exceeded with url: /local-static?location= (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),))

### ISSUE THREAD

**Issue by ssaranathan** [minio/minio-py#933]
Hi,
I get this error when the Django container comes up:

I am using minio:RELEASE.2019-10-02T21-19-38Z

Any idea what could be wrong ?

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 173, in handle
    if self.is_local_storage() and self.storage.location:
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 227, in is_local_storage
    return isinstance(self.storage, FileSystemStorage)
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 238, in inner
    self._setup()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 504, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/usr/local/lib/python3.6/site-packages/minio_storage/storage.py", line 434, in __init__
    presign_urls=presign_urls)
  File "/usr/local/lib/python3.6/site-packages/minio_storage/storage.py", line 65, in __init__
    self.bucket_name):
  File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 431, in bucket_exists
    self._url_open('HEAD', bucket_name=bucket_name)
  File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 1984, in _url_open
    region = self._get_bucket_region(bucket_name)
  File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 1919, in _get_bucket_region
    region = self._get_bucket_location(bucket_name)
  File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 1950, in _get_bucket_location
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 349, in urlopen
    kw['headers'].pop(header, None)
TypeError: pop() takes 2 positional arguments but 3 were given

**Comment by harshavardhana** [comment]
> I am using minio:RELEASE.2019-10-02T21-19-38Z
> 
> Any idea what could be wrong ?
> 
> Traceback (most recent call last):
> File "manage.py", line 22, in
> execute_from_command_line(sys.argv)
> File "/usr/local/lib/python3.6/site-packages/django/core/management/**init**.py", line 364, in execute_from_command_line
> utility.execute()
> File "/usr/local/lib/python3.6/site-packages/django/core/management/**init**.py", line 356, in execute
> self.fetch_command(subcommand).run_from_argv(self.argv)
> File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
> self.execute(*args, **cmd_options)
> File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
> output = self.handle(*args, **options)
> File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 173, in handle
> if self.is_local_storage() and self.storage.location:
> File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 227, in is_local_storage
> return isinstance(self.storage, FileSystemStorage)
> File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 238, in inner
> self._setup()
> File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 504, in _setup
> self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
> File "/usr/local/lib/python3.6/site-packages/minio_storage/storage.py", line 434, in **init**
> presign_urls=presign_urls)
> File "/usr/local/lib/python3.6/site-packages/minio_storage/storage.py", line 65, in **init**
> self.bucket_name):
> File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 431, in bucket_exists
> self._url_open('HEAD', bucket_name=bucket_name)
> File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 1984, in _url_open
> region = self._get_bucket_region(bucket_name)
> File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 1919, in _get_bucket_region
> region = self._get_bucket_location(bucket_name)
> File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 1950, in _get_bucket_location
> headers=headers)
> File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 349, in urlopen
> kw['headers'].pop(header, None)
> TypeError: pop() takes 2 positional arguments but 3 were given

@ssaranathan looks like some installation screw up on your end. your installation of urllib3 conflicts

**Comment by ssaranathan** [comment]
Hi,
These are the modules that I have.  Any idea which one could be conflicting with the urllib3?
asgi-redis==1.4.3
boto3==1.9.88
botocore==1.12.88
commonmark==0.5.4
django==1.11.23
django-allauth==0.40.0
django-filter==2.1.0
django-import-export==0.5.1
djangorestframework==3.9.3
djangorestframework-expiring-authtoken==0.1.4
django-cors-headers==1.3.1
django-rest-auth[with_social]==0.9.2 
django-ses==0.8.5
django-sslserver==0.21
docker-compose==1.21.0
drfdocs==0.0.11
drf-yasg==1.11.0
pika==0.10.0
pickleshare==0.7.4
Pillow==6.2.0
psycopg2==2.7.3.2
PyYaml==4.2b1
proc==0.10.1
rstr==2.2.5
sendgrid==5.6.0
django-minio-storage==0.2.2
uwsgi
boto==2.43.0
django-storages==1.7.1
python-memcached==1.58
raven==5.32.0
datadog==0.14.0
coveralls==1.1
django-autofixture==0.12.1
django-debug-toolbar==1.8
django-extensions==1.7.8
django-silk==1.0.0
django-spaghetti-and-meatballs==0.2.2

**Comment by harshavardhana** [comment]
> botocore==1.12.88

most probably this @ssaranathan

**Comment by ssaranathan** [comment]
Hi @harshavardhana ,
I removed botocore.. still having the same issue.

Thanks for your help,

**Comment by harshavardhana** [comment]
> I removed botocore.. still having the same issue.

you need to remove urllib3 @ssaranathan and re-install minio-py

**Comment by ssaranathan** [comment]
Hi @harshavardhana , thanks for your tips.  I have not explicitly installed urllib3 ( I don't see it in my list of modules).  I am using only django-minio-storage==0.3.7.  Any ideas ?

This is my list of updated modules:
asgi-redis==1.4.3
boto3==1.9.88
commonmark==0.5.4
django==1.11.23
django-allauth==0.40.0
django-filter==2.1.0
django-import-export==0.5.1
djangorestframework==3.9.3
djangorestframework-expiring-authtoken==0.1.4
django-cors-headers==1.3.1
django-rest-auth[with_social]==0.9.2 
django-ses==0.8.5
django-sslserver==0.21
docker-compose==1.21.0
drfdocs==0.0.11
drf-yasg==1.11.0
pika==0.10.0
pickleshare==0.7.4
Pillow==6.2.0
psycopg2==2.7.3.2
PyYaml==4.2b1
proc==0.10.1
rstr==2.2.5
sendgrid==5.6.0
django-minio-storage==0.3.7
uwsgi
python-memcached==1.58
raven==5.32.0
datadog==0.14.0
coveralls==1.1
django-autofixture==0.12.1
django-extensions==1.7.8

**Comment by ssaranathan** [comment]
When I tried to uninstall urllib3, this is what I got:
Step 8/11 : RUN pip uninstall -y urllib3

 ---> Running in 169a9f96bd65

WARNING: Skipping urllib3 as it is not installed.

**Comment by ssaranathan** [comment]
Hi @harshavardhana , any clues ?  I am stuck with this issue in our production build.. Thanks for your help.

**Comment by ssaranathan** [comment]
Hi @harshavardhana , I made some more updates to the code.  Instead of reading the minio secret and key from the config map in the container, I hard coded them in the python code.  I also have a valid Digicert  signed certificate and I have that in the deployment yaml file of both Django and Minio ( I have both the Root and CA certs) and still getting the following error.

Try running with a higher verbosity level like: -v2 or -v3
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
chunked=chunked,
File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 381, in _make_request
self._validate_conn(conn)
File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 976, in validate_conn
conn.connect()
File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 370, in connect
ssl_context=context,
File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl.py", line 377, in ssl_wrap_socket
return context.wrap_socket(sock, server_hostname=server_hostname)
File "/usr/local/lib/python3.6/ssl.py", line 407, in wrap_socket
_context=self, _session=session)
File "/usr/local/lib/python3.6/ssl.py", line 814, in init
self.do_handshake()
File "/usr/local/lib/python3.6/ssl.py", line 1068, in do_handshake
self._sslobj.do_handshake()
File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "manage.py", line 22, in
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.6/site-packages/django/core/management/init.py", line 364, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.6/site-packages/django/core/management/init.py", line 356, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
self.execute(*args, **cmd_options)
File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
output = self.handle(*args, **options)
File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 173, in handle
if self.is_local_storage() and self.storage.location:
File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 227, in is_local_storage
return isinstance(self.storage, FileSystemStorage)
File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 238, in inner
self._setup()
File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 504, in _setup
self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
File "/usr/local/lib/python3.6/site-packages/minio_storage/storage.py", line 410, in init
object_metadata=object_metadata,
File "/usr/local/lib/python3.6/site-packages/minio_storage/storage.py", line 75, in init
self._init_check()
File "/usr/local/lib/python3.6/site-packages/minio_storage/storage.py", line 93, in _init_check
elif not self.client.bucket_exists(self.bucket_name):
File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 431, in bucket_exists
self._url_open('HEAD', bucket_name=bucket_name)
File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 1984, in _url_open
region = self._get_bucket_region(bucket_name)
File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 1919, in _get_bucket_region
region = self._get_bucket_location(bucket_name)
File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 1950, in _get_bucket_location
headers=headers)
File "/usr/local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 336, in urlopen
response = conn.urlopen(method, u.request_uri, **kw)
File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 765, in urlopen
**response_kw
File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 765, in urlopen
**response_kw
File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 765, in urlopen
**response_kw
[Previous line repeated 1 more times]
File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 725, in urlopen
method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 439, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='***ibm.com', port=443): Max retries exceeded with url: /local-static?location= (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),))`

**Comment by ssaranathan** [comment]
The K8S pod was looking at the wrong SSL certificates.  This can be closed now.  Thanks.
