### ISSUE TITLE
minio set_bucket_notification gives error "InvalidArgument: message"

### ISSUE THREAD

**Issue by Shashikant255** [minio/minio-py#955]
I am trying to set_bucket_notification in minio. I am using below code to do so.
```
minioClient = Minio(
                  'ip:port',
                  access_key='minio',
                  secret_key='miniotest',
                  secure=False
                  )
config = {
            "QueueConfigurations":[
            {
              "Id": "1",
              "Arn": "arn:minio:sqs::_:webhook",
              "Events": [
                "s3:ObjectCreated:Put"
              ],
              "Filter": {
                "Key": {
                  "FilterRules": [
                    {
                      "Name": "suffix",
                      "Value": ".jpg"
                    }
                  ]
                }
              }
            }
          ]
          }
minioClient.set_bucket_notification("my-bucketname", config)
```
This gives below error:-
> Traceback (most recent call last):
>   File "minio_notification.py", line 151, in <module>
>     minioClient.set_bucket_notification(bucket_name="testbucket", notifications=config_not.dict(exclude_none=True, by_alias=True),)
>   File "/usr/local/lib/python3.6/dist-packages/minio/api.py", line 527, in set_bucket_notification
>     content_sha256=content_sha256_hex
>   File "/usr/local/lib/python3.6/dist-packages/minio/api.py", line 2225, in _url_open
>     object_name).get_exception()
> minio.error.InvalidArgument: InvalidArgument: message: Invalid Argument

Can anyone help me to set_bucket_notification? 
@harshavardhana @kannappanr

**Comment by Shashikant255** [comment]
This error is solved by setting MINIO_NOTIFY_WEBHOOK_ENABLE, MINIO_NOTIFY_WEBHOOK_ENDPOINT and MINIO_NOTIFY_WEBHOOK_QUEUE_LIMIT variable.
`docker run -e MINIO_ACCESS_KEY=minio -e MINIO_SECRET_KEY=minio -e MINIO_NOTIFY_WEBHOOK_ENABLE=on -e MINIO_NOTIFY_WEBHOOK_ENDPOINT=http://<ip>/backend/v1/storage/events -e MINIO_NOTIFY_WEBHOOK_QUEUE_LIMIT=1000 -it  -v data:/data -p 9000:9000 minio/minio server /data`
