### ISSUE TITLE
Unable to create buckets

### ISSUE THREAD

**Issue by danilopeixoto** [minio/minio-py#980]
Hi,

I can't create buckets using the Python SDK.

Versions:
- Python 3.7.0
- MinIO SDK 6.0.0

Source code:

```python
from minio import Minio


client = Minio('play.min.io',
  access_key = 'Q3AM3UQ867SPQQA43P2F',
  secret_key = 'zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG',
  secure = True)

client.make_bucket('mytestbucket42', location = 'us-east-1')

```

Traceback:

```
Traceback (most recent call last):
  File "storage.py", line 9, in <module>
    client.make_bucket('mytestbucket42', location = 'us-east-1')
  File "C:\Users\user\Downloads\app\api\services\venv\lib\site-packages\minio\api.py", line 329, in make_bucket
    headers=headers)
  File "C:\Users\user\Downloads\app\api\services\venv\lib\site-packages\urllib3\poolmanager.py", line 325, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
  File "C:\Users\user\Downloads\app\api\services\venv\lib\site-packages\urllib3\poolmanager.py", line 240, in connection_from_host
    return self.connection_from_context(request_context)
  File "C:\Users\user\Downloads\app\api\services\venv\lib\site-packages\urllib3\poolmanager.py", line 253, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
  File "C:\Users\user\Downloads\app\api\services\venv\lib\site-packages\urllib3\poolmanager.py", line 274, in connection_from_pool_key
    pool = self._new_pool(scheme, host, port, request_context=request_context)
  File "C:\Users\user\Downloads\app\api\services\venv\lib\site-packages\urllib3\poolmanager.py", line 208, in _new_pool
    return pool_cls(host, port, **request_context)
  File "C:\Users\user\Downloads\app\api\services\venv\lib\site-packages\urllib3\connectionpool.py", line 893, in __init__
    **conn_kw
  File "C:\Users\user\Downloads\app\api\services\venv\lib\site-packages\urllib3\connectionpool.py", line 200, in __init__
    self.pool = self.QueueCls(maxsize)
TypeError: __init__() missing 3 required positional arguments: 'port', 'username', and 'password'
```

Thanks.

**Comment by kannappanr** [comment]
@danilopeixoto I tried `minio-py` `6.0.0` and `python` version `3.6.8` and unable to see the issue

**Comment by balamurugana** [comment]
@danilopeixoto As the error occured at urllib3, please upgrade it and try again.

**Comment by kannappanr** [comment]
@danilopeixoto closing this as answered. Please let us know if it still happens
